### ISSUE TITLE
NodeBB v0.6.0 Mongo Import 0.3.0

### ISSUE THREAD

**Issue by limitmaker** [akhoury/nodebb-plugin-import#101]
State: busy, by event: importer.start | Phase: categoriesImportStart Progress: 0.00%

It's not moving past this

**Comment by akhoury** [comment]
how does the weekend of January 10 sounds? what is your timezone ?

**Comment by limitmaker** [comment]
I'm Central time.  Do you think in the mean time you could transfer me a mongo dump of the database I sent you?  I want to see all the issues I'm going to run into with nodebb with a larger forum and older data.

Hope the holidays were great!  all the optimism around the New Years is nice. :)

**Comment by akhoury** [comment]
Yea, I think I still have the Mongo DB, but not 100% sure, I will check
later tonight

**Comment by limitmaker** [comment]
I was able to get it to work with 6.1-dev.  Looks like they made it there!  Thank you! I'll let you know if I run into more problems.  I thought there was a bbcode to markdown converter with your import plugin 

     On Monday, January 5, 2015 1:44 PM, Aziz Khoury <notifications@github.com> wrote:
   

 Yea, I think I still have the Mongo DB, but not 100% sure, I will check
later tonight

**Comment by akhoury** [comment]
>  I thought there was a bbcode to markdown converter with your import plugin

there is, It's in the Post-Import tools, you must convert after the import is done, not during.
https://camo.githubusercontent.com/0a31a0c76572dfa09c03b4319245bb940986f229/687474703a2f2f692e696d6775722e636f6d2f6161574c4f52692e706e67

**Comment by limitmaker** [comment]
Oh I'm just dumb. Will this also convert private messages? 

     On Monday, January 5, 2015 11:26 PM, Aziz Khoury <notifications@github.com> wrote:
   

 
I thought there was a bbcode to markdown converter with your import plugin
there is, It's in the Post-Import tools, you must convert after the import is done, not during.
https://camo.githubusercontent.com/0a31a0c76572dfa09c03b4319245bb940986f229/687474703a2f2f692e696d6775722e636f6d2f6161574c4f52692e706e67—

**Comment by akhoury** [comment]
oh, not really, but I can add that, open a ticket so I would remember. I didn't know that messages included bbcode formatting.
