### ISSUE TITLE
Thread close aftter import

### ISSUE THREAD

**Issue by h3ku** [akhoury/nodebb-plugin-import#102]
After importing from vbulletin the threads close automatically, how keep they open?

Thanks.

**Comment by akhoury** [comment]
What do you mean close? can you look at an example thread record in the database? is `locked == 1` ?

**Comment by nhlpl** [comment]
Yes, they are locked after using your import tool. I have tested it on vBulletin 3.8.x database and NodeBB 0.6.1.

**Comment by akhoury** [comment]
I will do some digging this week

**Comment by akhoury** [comment]
should be good now with `nodebb-plugin-import@0.3.2` re-open if it happens again, and i am going to need a sample DB dump.
