### ISSUE TITLE
user created groups

### ISSUE THREAD

**Issue by limitmaker** [akhoury/nodebb-plugin-import#105]
In vbulletin we had user created groups, I was wondering if there are plans to convert those as well!

Then all that would be left from vbulletin would be blog data and profile comments.

Maybe we can throw all the profile comments into private messages until nodebb officially supports profile comments (if they ever do)?

**Comment by akhoury** [comment]
> user created groups

i am not sure. Does NodeBB supports user created groups?

We can also preserve the profile comments somewhere sure.

**Comment by limitmaker** [comment]
https://community.nodebb.org/topic/3612/sneak-peek-of-user-created-groups-in-v0-6-1/12

Looks to be!

**Comment by limitmaker** [comment]
Hey Akhoury, just checking in.  I've played around with the user groups now and it's not as intended (in my mind)

So I just need to find a place to put all the usergroups (make them into forum categories?), the blogs (put them in blog category for now?), and user profile comments (put them in private messages?)

Then everything from a vbulletin 4 default install will be transferred over. :D

**Comment by akhoury** [comment]
kind of like a temporary place? I can do that, I don't love it thought, but I will take a look

**Comment by limitmaker** [comment]
Yea.  Understandable.  I don't like it either.This is just the fastest way to get everything out of vbulletin now until similar features exist.

**Comment by akhoury** [comment]
Groups are not supported
