### ISSUE TITLE
Partial database

### ISSUE THREAD

**Issue by nhlpl** [akhoury/nodebb-plugin-import#107]
Import plugin should skip empty tables and use only those populated by data. I have tested a small portions of data just to check how it works.

Import tool stops working when there is no forum admin and members in MySQL database (only a real table structure with a partial data). 

Let say I have populated MySQL rows with all categories and something more which is executed by import script after members table. Only categories will be imported and there is no way to import posts and private messages.

It can be fixed by manually adding more records to the database. Not a real bug and will not affect those who use a whole database dump.

Tested on IP Board 2.3.x > NodeBB 0.6.1.

**Comment by akhoury** [comment]
i see your point, but sometimes, some data records depend on others to exist as well.

For example:

Each topic depends on a parent-category and a user
Each post depends on a parent-topic and a user
