### ISSUE TITLE
importer stuck in infinite loop?

### ISSUE THREAD

**Issue by bdharrington7** [akhoury/nodebb-plugin-import#115]
Hey @akhoury been trying to write an [importer for vanilla forums](https://github.com/bdharrington7/nodebb-plugin-import-vanilla) based on your example for UBB. I've got something that seems to compile fine now, but I have a logging statement after creating the Categories query, and it would just print the query endlessly. Nothing actually gets imported. I'm using NBB 0.7.x commid 1c94866ab3e6791fc233358bc157f06b05313d48 

It doesn't seem like it would be related to something like the NBB version but I could be wrong.

**Comment by akhoury** [comment]
Well, the importer keeps calling the query until it returns 0 rows - 
you have a semicolon here 
https://github.com/bdharrington7/nodebb-plugin-import-vanilla/blob/master/index.js#L136

remove it to let the Limit logic work.

**Comment by akhoury** [comment]
by the way, I just published the 0.3.9 version which is compatible with a very recent hash of NodeBB, 4 days old - your plugin is compatible with it as well, you don't have to change anything

**Comment by bdharrington7** [comment]
ugh, semicolons... Thanks!
