### ISSUE TITLE
[exporter] Esotalk

### ISSUE THREAD

**Issue by mondododo** [akhoury/nodebb-plugin-import#117]
I still cannot export from esotalk. Can you help me? thx

**Comment by akhoury** [comment]
I can't help without a sample database dump

**Comment by mondododo** [comment]
Hi akhoury, i just sent you an email. Please kindly check.
Thanks in advance.

**Comment by akhoury** [comment]
got it. Please note that I will be able to look at this week. Most likely the following weekend.

**Comment by mondododo** [comment]
Hi, any updates about this one?

**Comment by akhoury** [comment]
yea - just made some fixes and ran a successful test.
it seems like i can't re-fork a [fork|https://github.com/sub-lunar/nodebb-plugin-import-esotalk] of my original [repo|https://github.com/akhoury/nodebb-plugin-import-ubb], so I am going to need to create a new one, like a nodebb-plugin-import-esotalk2 or something.

Will do so tomorrow.

**Comment by mondododo** [comment]
Wow great! Thanks for working on this.

**Comment by akhoury** [comment]
no problem.- wasnt able to publish this week, will do it on the weekend

**Comment by akhoury** [comment]
published, https://www.npmjs.com/package/nodebb-plugin-import-esotalk2

make sure you select __nodebb-plugin-import-esotalk2__ and NOT __nodebb-plugin-import-esotalk__ from the list
