### ISSUE TITLE
MyBB import crashed on NodeBB v0.6.1

### ISSUE THREAD

**Issue by Firelad97** [akhoury/nodebb-plugin-import#119]
The log shows this: https://gist.github.com/Firelad97/7f2cf8d7c36f192d6c28

But the importer is still running: http://prntscr.com/7ajxuc
It just stays at `groupsImportDone 100%`

**Comment by akhoury** [comment]
looks like the mysql host is not reacheable
`EHOSTUNREACH` ? this is coming out the mysql module

**Comment by Firelad97** [comment]
Shouldn't be. I got username, password, host, port, database name and prefix correct. I'll try to take a look at mysql host again.

**Comment by Firelad97** [comment]
I've checked, yes I did got them correct. Though at the start, in web log, it says `server.connected`... Does that mean it is already connected to MySQL, but still crashes?

**Comment by akhoury** [comment]
can you try a higher NodeBB version?

https://github.com/akhoury/nodebb-plugin-import#works-with-nodebb-v070-dev-last-tested-against-224e3dc2632b2819ea2927abbd533d76f7286a0d

But i don't think that's the problem. 
__MySQL is not able to connect__, it's probably not a user/pass issues, the host is not reachable, 

could this be related?
https://forums.openshift.com/nodejs-set-up-a-connection-to-mysql-created-in-the-php-app

can you confirm that you can connect to the same mysql DB, the same NodeBB machine via

```
mysql -u username -h your.database.host.com -p
```

**Comment by Firelad97** [comment]
https://forums.openshift.com/nodejs-set-up-a-connection-to-mysql-created-in-the-php-app
It is related, and the only solution is to upgrade, unfortunately I can't afford it. So I can try importing from MySQL on same machine as NodeBB. I will look into it when it's morning here.

**Comment by akhoury** [comment]
ok fair enough, Im closing this issue as it's not related to this plugin, open another if you see one.

**Comment by Firelad97** [comment]
Looks like it works, so I'm not opening another issue. It imported everything I need, and it's very fast.
