### ISSUE TITLE
Can't use database from importer

### ISSUE THREAD

**Issue by Fidelix** [akhoury/nodebb-plugin-import#121]
First of all, I'm new to NodeJS development. I'm liking it so far (except for a few annoyances here and there).

I am extending development of nodebb-plugin-import-ipboard (forked and will send a PR once it's done) to support a bunch of stuff the current plugin does not currently support, for instance:

* IPB replies which are in a special blockquote format.
* Spoiler blocks
* Mentions
* A few more things...

On my nodebb-plugin-import-ipboard/index.js file, which I'm requiring from a manual test.js file (so it's not running inside NodeBB!), I placed a:
var db = require('nodebb-plugin-import/server/db');

But when I try to use it like this:
var imported_post = db.getObject("_imported_post:1566");
I just get "undefined".
I can see on the debugger variables Redis is loaded (but I don't know if it was loaded correctly.)

I also tried loading data instead of db:
var data = require('nodebb-plugin-import/server/data');
and
var imported_post = data.getImportedPost("1566");

And I just get undefined.
Can someone tell me what I'm doing wrong?

Thanks!

**Comment by akhoury** [comment]
Commit your changes, ill take a look.

by the way, the import plugin does support spolier blocks, mentions and blockquotes if they are BBcode or HTML, what is the format that IPB uses? can you share few examples?

**Comment by Fidelix** [comment]
Newer versions of IPB do not use BBCode by default, they encourage otherwise.

Here's a reply with a spoiler block:
```
<blockquote  class="ipsBlockquote" data-author="Demetrius" data-cid="1566" data-time="1376515860">
<div>
<p>Olha, eu assisti o Yu-gi-oh GX, at&#233; que foi legalzinho. Fica a seu crit&#233;rio assistir ou n&#227;o.</p>
</div>
</blockquote>
<p>Eu achei brisado demais</p>
<p>[spoiler]Escola de Monstros &#160;de Duelo? huashua t&#225; parecendo Pok&#233;mon, cade escolas normais? A taxa de analfabetismo deve ser grande :ha: [/spoiler]</p>
```

Here's a mention:
```
@[member="Kaitei"]
```

**Comment by Fidelix** [comment]
Here's the commit:
https://github.com/Fidelix/nodebb-plugin-import-ipboard/commit/ac29927b715d40f98abc5cf8c09bcd1b7d232d79

I'm only just getting started, so there isn't much yet, and it's not properly organized...

**Comment by akhoury** [comment]
ill take a look this weekend

**Comment by akhoury** [comment]
@Fidelix - the importer plugin imports all content untouched. So You can run the import normally, then put this script below in a .js script and run it. 

```javascript
// assuming this script in the nodebb-plugin-import directory

// NOTE: this is NOT a complete script, just a hint.

// load my custom data module that has many iterative helpers
var Data = require ('./server/data.js')

// using your regex here, I haven't really tested it
// I would always recommend against parsing HTML via regex, it never works right, even when you think it does.
var ipb_reply_ex = /<blockquote[\s\S]{1,80}?data-cid="([\d]{1,10}?)"[\s\S]{0,100}?>([\s\S]+?)<\/blockquote>/gi;

Data.eachPost(function(post, next) {
        // 'post' is the NodeBB post hash, but augmented with the importer stuff
        // 'next' is your callback function, when you're done from this specific record
       var new_content = '';
       var reply_matches = ipb_reply_ex.exec(post._imported_content);
        if (reply_matches && reply_matches.length == 3) {
             // let's just assume reply_matches[1] is your _imported_post id,        
            Data.getImportedPost(reply_matches[1], function (err, _imported_post) {
               if (err) { // if there is an error, maybe that specific post was never imported for other reasons.
                  // just call next to skip it - or you can choose to parse it without the pid
                  return next();
               }
               
                // no error, great, the _imported_post has the original _pid and the new pid
               // you can start building your string
              // _imported_post.pid is the new post id                    
              // etc ....  build new_content
             ......
             .......
             ........
             
              // assuming you have the new content, you can now save

              Posts.setPostFields(_imported_post.pid, {content: new_content}, function (err) {
                  if (err) { 
                       return next(err);
                  }
                  next(); // post saved!
              });
            });   
        } else {  
           // if there isn't a match, you still want to call next() otherwise, it would hang
           next();
        }
    }, 
    {
        async: true, // make sure each set of iterations waits for the next batch
        eachLimit:  10 // limit 10 at the same time or whatever
    },
    function (err) {
         // when ALL of them are done or an error occurs
         if (err) {
             throw err;
         }
         console.log("DONE!!");
   }
);

```

# but why?
Why do you need to reference the old post ids? isn't the username enough? If you want, the Importer have a built in converter to convert the blockquotes to Markdown. If you want I can just add support for `data-author` to quote the Author. @bdharrington7 [recently added](https://github.com/akhoury/html-md-optional_window/pull/2) support for `rel` atttribute as the author

Also, the `[spolier]`is also supported, this one is bbcode.

As for the mentions, you don't have to write a script, we can write a quick custom JS regex replacement to run in each post import, See screenshot.
![screen shot 2015-06-21 at 11 38 32 am](https://cloud.githubusercontent.com/assets/1398375/8272272/1fba9960-180a-11e5-89b0-364f9534f048.png)

Someone recently import IPB which was a mix of html and bbcode together
https://github.com/akhoury/nodebb-plugin-import/issues/112

**Comment by Fidelix** [comment]
@akhoury this is awesome, thanks for all the tips and all the help.

The problem with the username is that they're not always correct - some users can change usernames on IPB, and IPB has different requirements than NodeBB. IPB accepts spaces and a bunch of special characters on usernames (I know, it sucks), and NodeBB does not, so the usernames on NodeBB are different than what they were on IPB after the conversion.

Also, on IPB, when you reply to another post you can just click on the title of the reply blockquote and it takes you to the reply post. Would be nice to have that as well.

For the spoiler stuff, you're right. A simple regex replacement would suffice, but I think it would be nice to have this in the importer as an option (not forced!) to keep things simpler.

I will try to post-process the posts as you're suggesting, and I'll let you know if I succeed.

**Comment by Fidelix** [comment]
This is the code I'm using:
https://gist.github.com/Fidelix/5b860d9be476d4fc18df

I know, not very pretty, but it seems to work. Perhaps this will help other people in the future.
I'll try to keep the gist updated.
