### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Fidelix** [akhoury/nodebb-plugin-import#124]
There's probably a memory leak somewhere in the post-importer.

It happens whenever I try to use the post-importer and select to convert HTML or BBCode to Markdown.

- I have 89141 imported posts that I need to process. All coming from IPB.
- Redis 3.0.2.
- NodeBB v0.7.0 + convert plugin from master.
- If I don't convert anything, it runs fast and well.
- I'm only checking to convert "posts".
- Markdown plugin and every other related plugin is deactivated.
- It crashes after a long time processing - every minute that passes, processing speed is slower and slower. At first, it does 20-50 posts per second, and before it breaks 1-2 per second.

I can provide the Redis DB in private if anyone needs it (~300MB).

Is there anything I can do to find the culprit?

**Comment by akhoury** [comment]
hmm.. 
* which version of NodeBB?
* which version of the importer?
* which version of Redis?
* give me the __ALL__ the specs of your machine? (the server that is running NodeBB)
* does it make a difference if you convert "HTML to Markdown" or "BBCode to Markdown"?
* have you tried this > https://github.com/akhoury/nodebb-plugin-import#redis-note
* do you have Server or Verbose logging on? you shouldn't
![screen shot 2015-07-04 at 10 40 15 am](https://cloud.githubusercontent.com/assets/1398375/8508302/1fec34fa-2239-11e5-8cea-322c394e982d.png) 

I've converted over 3 millions posts before, I suspect this is a new bug from recent changes. I'd love to test with your data - maybe send it over via Google Drive or dropbox - i will permanently delete it when done.

**Comment by Fidelix** [comment]
@akhoury the info you requested is on the OP.

```
does it make a difference if you convert "HTML to Markdown" or "BBCode to Markdown"?
```
No. But the HTML to Markdown takes a bit longer to crash.

```
have you tried this > https://github.com/akhoury/nodebb-plugin-import#redis-note
```
Yes.

```
do you have Server or Verbose logging on? you shouldn't 
```
Yes. Let me try to disable it (but I'm pretty sure the problem occurs even when logging is completely disabled).

My *VIRTUAL* machine specs:
Kernel: 4.0.6-1-ARCH
i7 4770 - 4 cores + 4 threads
16GB
SSD 60GB RAID 0

I'll try to generate heap dumps on 0.5% and 12% (it crashes around 15%) and compare them to see what's destroying the memory.

**Comment by akhoury** [comment]
> the info you requested is on the OP.

Sorry, i just woke up, lol - i read FATAL ERROR and stop reading after that.

send me your db dump, I don't have a large at hand right now.

**Comment by Fidelix** [comment]
Here's a screenshot of the heap dump:
![image](https://cloud.githubusercontent.com/assets/309092/8508482/ec497f94-2248-11e5-8a88-81e870a8d3bc.png)

There are many thousands of occurrences of this error.
This is most likely the source of the problem.

Still want the DB dump? It'll take a while for me to upload it (slow connection), but I'll gladly do it if it helps sort this out.

**Comment by Fidelix** [comment]
Apparently this problem is solved on jsdom 1.0
https://github.com/apparentlymart/node-angularcontext/issues/5

But nodejs is stuck on 0.8.
What do you recommend?

**Comment by Fidelix** [comment]
Seems we're stuck with an ancient version of jsdom. Maybe it would help if we upgraded...

**Comment by Fidelix** [comment]
Tried with all kinds of logging disabled. Same problem, nearly identical memory heap.

**Comment by akhoury** [comment]
can you send me just an example post-content that triggers this error, I think i might have a workaround.
bentael@gmail.com

**Comment by Fidelix** [comment]
I'm sorry, I don't know what an example post-content is.

You mean a json object like this?
```
HGETALL post:30000
{
  "uid": "522",
  "_imported_category_slug": "",
  "_imported_user_path": "",
  "content": "<p>Admito que até o episódio 3 eu tava achando o anime normal,mas depois desse episódio 4,deu uma upada de nivel absurda. Todo o lance do discurso me pareceu uma espécie de \"estopim\",acho que daqui pra frente vai pegar fogo.</p>\n",
  "_imported_topic_slug": "",
  "_imported_toPid": "",
  "_imported_category_path": "",
  "deleted": "0",
  "editor": "",
  "pid": "30000",
  "_imported_tid": "750",
  "edited": "0",
  "_imported_topic_path": "",
  "_imported_guest": "",
  "_imported_ip": "",
  "relativeTime": "2014-05-02T15:22:32.000Z",
  "_imported_uid": "695",
  "_imported_pid": "30245",
  "reputation": "0",
  "votes": "0",
  "_imported_content": "<p>Admito que até o episódio 3 eu tava achando o anime normal,mas depois desse episódio 4,deu uma upada de nivel absurda. Todo o lance do discurso me pareceu uma espécie de \"estopim\",acho que daqui pra frente vai pegar fogo.</p>\n",
  "_imported_cid": "65",
  "tid": "658",
  "timestamp": "1399044152000",
  "_imported_path": "",
  "_imported_user_slug": ""
}
```

**Comment by Fidelix** [comment]
```
HGETALL _imported_post:1000
{
  "_pid": "1000",
  "_tid": "117",
  "_uid": "71",
  "_content": "<p>hahaha pode crer vou arrumar</p>\n",
  "_timestamp": "1376264604000",
  "_edittimestamp": "null",
  "imported": "true",
  "reputation": "0",
  "votes": "0",
  "edited": "0",
  "deleted": "0",
  "relativeTime": "2013-08-11T23:43:24.000Z",
  "_imported_pid": "1000",
  "_imported_uid": "71",
  "_imported_tid": "117",
  "_imported_content": "<p>hahaha pode crer vou arrumar</p>\n",
  "_imported_cid": "65",
  "_imported_ip": "",
  "_imported_guest": "",
  "_imported_toPid": "",
  "_imported_user_slug": "",
  "_imported_user_path": "",
  "_imported_topic_slug": "",
  "_imported_topic_path": "",
  "_imported_category_path": "",
  "_imported_category_slug": "",
  "_imported_path": "",
  "pid": "2041",
  "uid": "66",
  "tid": "86",
  "content": "<p>hahaha pode crer vou arrumar</p>\n",
  "timestamp": "1376264604000",
  "editor": "",
  "cid": "35"
}
```

**Comment by Fidelix** [comment]
By the way, it's not a specific post that triggers this error. Every time I run the convert process it breaks on a different post, because the memory usage grows gradually with every post.

**Comment by akhoury** [comment]
i was hoping that some sort of a unicode character is breaking the conversion. It doesn't look like this is the case

**Comment by Fidelix** [comment]
I created this script on nodebb root for testing purposes...
```
"use strict";
var async = require('async'),
  //db = require('./src/database.js'),
  Data = require('nodebb-plugin-import/server/data.js'),
  CONVERT_BATCH_LIMIT = 10;
var memwatch = require('memwatch-next');

memwatch.on('leak', function(info) {console.log(info)});

var brRe = /<br\s*(\/)?>/gmi;
var entities = new (require('nodebb-plugin-import/node_modules/html-entities')).AllHtmlEntities();
var window = require("nodebb-plugin-import/node_modules/jsdom-nogyp").jsdom(null, null, {features: {FetchExternalResources: false}}).parentWindow;
var htmlMd = require('nodebb-plugin-import/node_modules/html-md-optional_window');
function convert(str){
  str = str || '';
  str = entities.decode(str);
  str = htmlMd(str, {window: window}).replace(brRe, "\n");
  return str;
}
var hd;
var diff;

var convertedString = {string: 'HAHAHA'};


Data.countPosts(function(err, total) {
  var index = 0;
  Data.eachPost(
    function(post, next) {
      console.log(index++);
      if (index == 100){
        hd = new memwatch.HeapDiff();
      }
      if(post._imported_pid == 2000) {
        diff = hd.end();
        console.log(require('util').inspect(diff, true, 10));
      }
      if (post && post._imported_pid && post._imported_content) {
        convertedString.string = convert(post._imported_content);
        var zuba = 'zzz';
        // do something with string
        delete convertedString.string;
        next();
        //db.setObjectField('post:' + post.pid, 'content', htmlMd(post._imported_content), next);
      } else {
        next();
      }
    },
    {async: true, eachLimit: CONVERT_BATCH_LIMIT},
    function(err) {
      // when ALL of them are done or an error occurs
      if (err) {
        throw err;
      }
      console.log("DONE!!");
    });
});
```

The console output is like this - I'm breaking on inspect(diff):
```
/usr/bin/node --debug-brk=53440 --nolazy htmltomd.js
Debugger listening on port 53440
db.ready
{ growth: 2233768,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 868256,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 104952,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 52528,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 72528,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 109512,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 53184,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 83480,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 3047048,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 2004936,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 196856,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 574992,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
{ growth: 262104,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
0
1
2
3
...
1110
{ growth: 70655080,
  reason: 'heap growth over 5 consecutive GCs (13s) - -2147483648 bytes/hr' }
1111
1112
...
1542
{ before: { nodes: 407918, size_bytes: 52833763, size: '50.39 mb' },
  after: { nodes: 943361, size_bytes: 159044905, size: '151.68 mb' },
  change: 
   { size_bytes: 106211142,
     size: '101.29 mb',
     freed_nodes: 2439,
     allocated_nodes: 537882,
     details: 
      [ { what: 'Arguments',
          size_bytes: 0,
          size: '0 bytes',
          '+': 2,
          '-': 2 },
        { what: 'Array',
          size_bytes: 8858512,
          size: '8.45 mb',
          '+': 143491,
          '-': 513 },
        { what: 'BreakPoint',
          size_bytes: 480,
          size: '480 bytes',
          '+': 6,
          '-': 0 },
        { what: 'Buffer', size_bytes: 0, size: '0 bytes', '+': 1, '-': 1 },
        { what: 'Closure',
          size_bytes: -13752,
          size: '-13.43 kb',
          '+': 110,
          '-': 301 },
        { what: 'Code',
          size_bytes: 60776,
          size: '59.35 kb',
          '+': 339,
          '-': 121 },
        { what: 'Command', size_bytes: 0, size: '0 bytes', '+': 1, '-': 1 },
        { what: 'FSReqWrap',
          size_bytes: -32,
          size: '-32 bytes',
          '+': 0,
          '-': 1 },
        { what: 'Module',
          size_bytes: 480,
          size: '480 bytes',
          '+': 6,
          '-': 0 },
        { what: 'Multi',
          size_bytes: -72,
          size: '-72 bytes',
          '+': 1,
          '-': 1 },
        { what: 'Native',
          size_bytes: 90262,
          size: '88.15 kb',
          '+': 3,
          '-': 3 },
        { what: 'NativeBuffer',
          size_bytes: 0,
          size: '0 bytes',
          '+': 1,
          '-': 1 },
        { what: 'Object',
          size_bytes: 3520352,
          size: '3.36 mb',
          '+': 83307,
          '-': 197 },
        { what: 'Queue', size_bytes: 0, size: '0 bytes', '+': 1, '-': 1 },
        { what: 'RegExp',
          size_bytes: 216,
          size: '216 bytes',
          '+': 3,
          '-': 0 },
        { what: 'String',
          size_bytes: 81101856,
          size: '77.34 mb',
          '+': 34438,
          '-': 1054 },
        { what: 'TypeError',
          size_bytes: 587376,
          size: '573.61 kb',
          '+': 24474,
          '-': 0 },
        { what: 'core.DOMException',
          size_bytes: 336,
          size: '336 bytes',
          '+': 6,
          '-': 0 },
        { what: 'system / Context',
          size_bytes: -9048,
          size: '-8.84 kb',
          '+': 67,
          '-': 200 },
        [length]: 19 ] } }

Process finished with exit code 130
```

The first detections are probably false positives, while posts are being counted, etc...
But you can see the difference is very big. This is not a problem specific to my system, I think.
You'll be able to reproduce this easily with this script, I believe.

I tried using the original html-md library instead of your fork, and the end result was the same (the original actually consumed a little more memory). Ultimately, I think this leak is probably happening on jsdom and this is where nodeJS stuff gets too complicated for me.

It would be dandy if we could somehow replace jsdom with cheerio (or something similar) on html-md.

**Comment by akhoury** [comment]
for some reason i am not able to load the dump.rdb file you sent me :/ I am not sure what's going yet
I installed redis 3.0.2 and I can see the 300mb file getting loaded into memory, but my database is behaving like it had no keys/data at all. 

Anyways, i was trying to reproduce the issue outside of NodeBB, if the problem was truly JSDOM, then we should be able to reproduce it, however, I wasn't able to reproduce it yet, can you? I tried 3 millions iterations - and I didn't see any leaks - there is another factor involved.

```bash
npm install async
npm install jsdom-nogyp
npm install memwatch-next
npm install html-md-optional_window

node test.js
```

h3. test.js file
```javascript


var ITERATIONS = 3000000;
var CONCURRENT_LIMIT = 10;
var SAMPLE = "<p>Admito que até o episódio 3 eu tava achando o anime normal,mas depois desse episódio 4,deu uma upada de nivel absurda. Todo o lance do discurso me pareceu uma espécie de \"estopim\",acho que daqui pra frente vai pegar fogo.</p>\n";

var newFilledArray =  function(len, val) {
    var rv = new Array(len);
    while (--len >= 0) {
        rv[len] = val;
    }
    return rv;
};

var replaceLog = function (msg) {
    process.stdout.clearLine();  // clear current text
    process.stdout.cursorTo(0);
    process.stdout.write(msg);
};

var STRINGS = newFilledArray(ITERATIONS, SAMPLE);

var memwatch = require('memwatch-next');
var async = require('async');
var htmlToMd = require('html-md-optional_window');
var window = require("jsdom-nogyp").jsdom(null, null, {features: {FetchExternalResources: false}}).parentWindow;

var s = +new Date();
var count = 0;

memwatch.on('leak', function(info) {
    console.log('\nLEAK: ', info, '\n\n');
});

async.eachLimit(STRINGS, CONCURRENT_LIMIT,
    function(str, next) {
        var sss = htmlToMd(str, {window: window});
        count++;
        setTimeout(function() {
            sss += 'abc';
            replaceLog('count: ' + count + ', ' + (count/ITERATIONS*100).toFixed(1) + '%');
            next();
        }, 0);
    },
    function() {
        console.log("\n\ndone in", ((+ new Date()) - s)/ 1000, "seconds");
    });



```

**Comment by akhoury** [comment]
ill try it next with these 2 statements
```
            str = parser.toHTML(str);
            str = entities.decode(str);
```
maybe the leak is there

**Comment by Fidelix** [comment]
Forgot to tell you, I actually use DB 5 for my nodebb and not DB 0.

**Comment by Fidelix** [comment]
I tried to comment this line:
```
str = entities.decode(str);
```
and there was still a leakage.

Now, commenting htmlToMd made the whole process go very fast, and no leakage - memory usage only grew 133.44 kb over 1900 records. When this line is uncommented, it grows ~105MB

**Comment by Fidelix** [comment]
I think I cracked this, @akhoury.

We're calling this once:
```
var window = jsdom.jsdom(null, null, {features: {FetchExternalResources: false}}).parentWindow;
```

And performing a bunch of operations in this window. I think the garbage collector is unable to kick in here because the window stays open, and this variable is still in scope, and jsdom is called repeatedly inside htmlMd.

I found two ways to fix this:
Run node with --expose_gc and call this after htmlMd:
```
// If memory usage is > 130MB, force GC.
if (process.memoryUsage().heapUsed > 130000000) {
    global.gc();
  }
```
Still not ideal, we can't ship code like this.

Or, instantiate the window in the beginning of every loop instead of only once, and after running htmlMd:
```
// Important! Prevent memory leak.
window.close();
```

This fixed the problem for me.

**Comment by akhoury** [comment]
the whole point of `html-md-optional_window` is to NOT to that though. I am glad that worked out for you. 

But actually you don't have to create window nor pass it in - is it optional - see the original issue behind this fork.
https://github.com/neocotic/html.md/issues/42

See source here
https://github.com/akhoury/html-md-optional_window/blob/master/lib/md.js#L118-L127

see my note here
https://github.com/akhoury/nodebb-plugin-import/pull/125/files#r33945391

**Comment by Fidelix** [comment]
I understand, that's why I removed the comment.

But we have to create the window because we also need to close it. The original html-md does not allow specifying the window parameter, does it?

I tested all of this on another real data set (Imported from SMF) on a different computer with a different OS and NodeJS version and Redis version.

I was able to reproduce everything, including the memory leaks and the fix.

**Comment by akhoury** [comment]
> But we have to create the window because we also need to close it. The original html-md does not allow specifying the window parameter, does it?

I see.. yea, not the original html-md does not allow the window parameter.

> I was able to reproduce everything, including the memory leaks and the fix.

Ok, great. I'll merge your fix.

**Comment by akhoury** [comment]
https://github.com/akhoury/nodebb-plugin-import/pull/125

**Comment by akhoury** [comment]
also changed bbcode-to-markdown module, since this one also uses html-md

https://github.com/akhoury/bbcode-to-markdown/commit/85ef2666896ed70d6973e48c778d4558a34a4ad8

**Comment by Fidelix** [comment]
Thanks mate!

Perhaps some time in the future it would benefit speed if we ported html-md to use cheerio instead of jsdom, since we have to create the window on every loop.

Cheerio is considerably faster in my experience.

**Comment by akhoury** [comment]
Thank you!
Sure! I don't have a problem with Cheerio, but the next 3 months are fully booked for me.
