### ISSUE TITLE
ER_NO_SUCH_TABLE 'databaseXXXXXX.IPB_forums' doesn't exist

### ISSUE THREAD

**Issue by mudmanc4** [akhoury/nodebb-plugin-import#127]
exporter.error { [Error: ER_NO_SUCH_TABLE: Table 'databaseXXXXXXX.IPB_forums' doesn't exist]
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0 }

**Comment by akhoury** [comment]
different version?
take a screenshot of the list of tables and which IPB version are you using

you might need to use this fork
https://github.com/miranmirza/nodebb-plugin-import-ipboard

**Comment by mudmanc4** [comment]
![ipb-table-list](https://cloud.githubusercontent.com/assets/541312/8651517/5d429636-2947-11e5-85b9-891cba88f274.png)

IPB V 3.2.3

Attempted the git you mentioned, same error

**Comment by jacmoe** [comment]
Simply set the 'prefix' option to `ipb_`
That allowed me to at least import all users and all categories before crashing on the messages importer.. :(

**Comment by akhoury** [comment]
Will take a look when I get home

**Comment by akhoury** [comment]
should be fixed by now, see https://github.com/akhoury/nodebb-plugin-import/issues/141
