### ISSUE TITLE
Error on install: A templates directory was defined for this plugin, but was not found.

### ISSUE THREAD

**Issue by rainfarmer** [akhoury/nodebb-plugin-import#130]
After activation of this plugin, I'm getting this error when I reload the forum: 
warn: [plugins/nodebb-plugin-import] A templates directory was defined for this plugin, but was not found.

http://mydomain.com/admin/plugins/import doesn't work. 
And the plugin options don't show up in Admin

I'm using NodeBB v0.8.2, It's newer then the tested version of this plugin.
I also installed via FTP upload to the node_module folder and activation via Admin.
I turned off all other plugins.

Any ideas would be appreciated, in a rush to get this forum ready for an active community trapped on a horrible Vanilla forum.

**Comment by bdharrington7** [comment]
If you're really in a rush, you can install a 0.7.x version of nodeBB, do the import, then upgrade. 

If you can wait, I'm waiting on a refactor from @aziz to finish attachments and some others from vanilla (if you need that)

-Brian

**Comment by rainfarmer** [comment]
The current version of nodebb-plugin-import-vanilla is fine by mean (assuming it works with my version), but first I need to get nodebb-plugin-import working. 

Any ideas on how to fix the error?
I don't mind diving into the code, but I'm out of my element as to where to start.

I found that the template directorys are being called here: https://github.com/akhoury/nodebb-plugin-import/blob/master/server/routes.js

I see the broken file being called, not sure what's wrong:
var router = params.router;
var prefix = '/admin/plugins/' + Plugin.json.nbbId;
router.get(prefix, middleware.applyCSRF, middleware.admin.buildHeader, Plugin.render);

**Comment by bdharrington7** [comment]
I haven't been able to try it on 0.8.2, but I know the import plugin works on nodebb 0.7.x. You can downgrade your nodebb, do the import, then upgrade to the latest version of nodebb, which will get you up to speed the fastest 

-Brian

**Comment by akhoury** [comment]
unable to reproduce.
