### ISSUE TITLE
[exporter] Discourse

### ISSUE THREAD

**Issue by julianlam** [akhoury/nodebb-plugin-import#131]
@akhoury A database dump sample (of dubious validity) can be found [on the TDWTF forum](https://what.thedailywtf.com/t/discourse-database-dump-for-testing/51356/46). Direct link to the dump: https://what.thedailywtf.com/uploads/default/original/3X/9/3/93cd01a0a2d43fdf14c044fe6c3404764b4e35ea.gz

**Comment by BenLubar** [comment]
A quick note as this confused me when I started trying to write a converter: Discourse database backups restore to the `restore` schema, so you have to do `FROM restore.users` instead of just `FROM users`.

**Comment by riking** [comment]
```
$ tar zxvf backup-file.tar.gz
# you now have the dump.sql and meta.json files
$ DATABASE=import_discourse
$ psql $DATABASE < dump.sql
$ psql $DATABASE <<END
DROP SCHEMA IF EXISTS backup CASCADE;
ALTER SCHEMA public RENAME TO backup;
ALTER SCHEMA restore RENAME TO public;
END
$ bundle exec rake db:migrate
```

**Comment by BenLubar** [comment]
https://github.com/BenLubar/nodebb-plugin-import-discourse

Still needs posts/topics/votes/messages.

**Comment by julianlam** [comment]
:+1:

**Comment by akhoury** [comment]
@BenLubar awesome! just added it to the list of exporters https://github.com/akhoury/nodebb-plugin-import/commit/134ea8156bf1be465f98c1271fa2af7b8ddacefc (it's not published yet, I am in the process of getting the importer compatible with 0.8.2 almost done, there are still few glitches, ETA this weekend)

let me know if you run into any issues! i'll be glad to help.

**Comment by tiazzz** [comment]
@akhoury Sorry to butt in on this issue, but you mentioned getting the importer ready for 0.8.2 - any ETA on that?

**Comment by akhoury** [comment]
> this weekend

17 days ago :/ 

I ran into a couple of issues, it was late so I gave up, I will give it another try this Saturday.

**Comment by akhoury** [comment]
@tiazzz nodebb-plugin-import@0.3.12 is now compatible with NodeBB v0.8.2

But I took out the discourse exporter option out of it because it's not complete yet, pending @BenLubar's repo https://github.com/BenLubar/nodebb-plugin-import-discourse

**Comment by tiazzz** [comment]
@akhoury Many thanks! I'll give it a spin once time allows.

**Comment by BenLubar** [comment]
@akhoury I'm not super-familiar with nodejs, redis, or NodeBB, but here's what my import script outputs on a fresh docker install of NodeBB 0.8.2:

```
exporter.ready
controller.state { now: 'busy', event: 'importer.start' }
importer.start undefined
importer.phase { phase: 'purgeCategories+Topics+PostsStart', data: undefined }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.ready undefined
exporter.ready undefined
importer.progress { count: 0, total: 1, percentage: 0 }
importer.warn purgeCategories+Topics+PostsStart : [[error:no-privileges]]
[nodebb-plugin-import] importer.warn purgeCategories+Topics+PostsStart : [[error:no-privileges]]
importer.progress { count: 1, total: 1, percentage: 100 }
importer.phase { phase: 'purgeCategories+Topics+PostsDone', data: undefined }
importer.phase { phase: 'purgeUsersStart', data: undefined }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.progress { count: 1, total: 1, percentage: 100 }
importer.phase { phase: 'purgeUsersDone', data: undefined }
importer.phase { phase: 'purgeMessagesStart', data: undefined }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.progress { count: 1, total: 1, percentage: 100 }
importer.phase { phase: 'purgeMessagesDone', data: undefined }
importer.phase { phase: 'resetGlobalsStart', data: undefined }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.progress { count: 1, total: 1, percentage: 100 }
importer.phase { phase: 'deleteTmpImportedSetsAndObjectsStart',
  data: undefined }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.phase { phase: 'deleteTmpImportedSetsAndObjectsDone',
  data: undefined }
importer.progress { count: 1, total: 1, percentage: 100 }
importer.progress { count: 1, total: 1, percentage: 100 }
importer.phase { phase: 'resetGlobalsDone', data: undefined }
importer.phase { phase: 'groupsImportStart', data: undefined }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.success Importing 6 groups.
[nodebb-plugin-import] importer.success Importing 6 groups.
importer.progress { count: 1, total: 6, percentage: 16.666666666666664 }
22/10 18:26 [7] - error: Error: ERR value is not a valid float
    at ReplyParser.<anonymous> (/opt/nodebb/node_modules/redis/index.js:305:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/nodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/opt/nodebb/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
```

If I remove everything having to do with groups from the importer, it works, but I don't want to release it with missing features.

**Comment by akhoury** [comment]
@BenLubar  - I will give it a shot next week.

@julianlam that discourse thread is unreadedle, do you have any idea what version of Discourse this dump is against?

**Comment by BenLubar** [comment]
@akhoury the specific post with the dump is [this one](https://what.thedailywtf.com/t/discourse-database-dump-for-testing/51356/47?u=ben_lubar).

The last `schema_migration` added was 20150901192313, so somewhere around version 1.4.0.

**Comment by akhoury** [comment]
@BenLubar 

I just successfully tested and imported against a fresh fork of you repo, using the latest version of [nodebb-plugin-import@0.3.13](nodebb-plugin-import@0.3.13)

demo
http://100.0.52.21:4567 (i will leave this running few days, or if I get dos-attacked)

Looks good, didn't get any concerning errors, just few warnings that some votes weren't imported (9 out of 83 were skipped) - not sure that's a major concern, if my assumption that this data dump is just a snapshot in time and some tables keys may not be available.

however, i am still following up with @julianlam since he mentioned that thedailywtf is planning on using a likes plugin instead the core votes feature - that might require some adjustments, but I am not sure which plugin is that? can you clarify?

aside from the `likes`, when you get a chance,  give it a shot, let me know if you're still seeing errors.

**Comment by bdharrington7** [comment]
@akhoury that'll happen self-votes are allowed in the forum being updated; nodebb doesn't allow votes on your own post

**Comment by julianlam** [comment]
Let me know if if you guys need a server to trash on :+1:

**Comment by akhoury** [comment]
that's done - new issues with this specific exporter needs to be filed under this repo:

https://github.com/BenLubar/nodebb-plugin-import-discourse
which im watching
