### ISSUE TITLE
ER_ACCESS_DENIED_ERROR: Access denied for   user 'username'@'wrongserver' (using password: YES)

### ISSUE THREAD

**Issue by rainfarmer** [akhoury/nodebb-plugin-import#132]
Hi, I've got the importer running for Vanilla Forums but it freezes at importing groups:
I get this response from the client log:

    current phase: groupsImportDone
    Importing 0/0 groups took: 0.00 seconds
    Importing 0 groups.
    current phase: groupsImportStart
    current phase: resetGlobalsDone
    current phase: deleteTmpImportedSetsAndObjectsDone
    current phase: deleteTmpImportedSetsAndObjectsStart
    current phase: resetGlobalsStart
    current phase: purgeMessagesDone
    current phase: purgeMessagesStart
    current phase: purgeUsersDone
    current phase: purgeUsersStart
    current phase: purgeCategories+Topics+PostsDone
    current phase: purgeCategories+Topics+PostsStart

There is an error on the server log:

    23/9 01:29 [18747] - [31merror [39m: Error: ER_ACCESS_DENIED_ERROR: Access denied for   user 'username'@'wrongserver' (using password: YES)
I can see that it's using the local server ip, which is wrong. In the plugin menu, I entered a mysql address for a DB on a different server. I can connect to the mysql server via terminal, using:

     mysql -u user -h mysql.server.com -p

NodeBB v0.7.0
Node.js v0.11.16
Vanilla v2.1
Using the master version of nodebb-plugin-import-vanilla and nodebb-plugin-import

I used correct DB login and prefix GDN_
Everything else is default settings.
Any ideas?

**Comment by rainfarmer** [comment]
I was able to fix the issue:

Had to setup remote access for my Dreamhost mySQL DB.

I had thought the error message was connecting to the wrong server:

    Access denied for   user 'username'@'wrongserver'
But, dur, it was just blocking that server (which was my local dns), not trying to connect to it.

**Comment by bdharrington7** [comment]
glad you figured it out, hope this helps someone else with a remote DB

**Comment by akhoury** [comment]
@rainfarmer cool - let us know if you're having any other issues.
