### ISSUE TITLE
Import bookmarks

### ISSUE THREAD

**Issue by bdharrington7** [akhoury/nodebb-plugin-import#134]
Since NBB stores bookmarks on the server, :tada: would be nice to be able to import that information as well

**Comment by akhoury** [comment]
what do you mean by bookmarks? are these also known as favorites?

**Comment by bdharrington7** [comment]
no, the placeholders for when you're browsing a topic, and come back on another device, and it takes you to the place you left off

**Comment by akhoury** [comment]
hmm, i dont know, this is not really content though, we could i guess, do you of any other forum that does that? (so we can use it as a test case)

**Comment by bdharrington7** [comment]
Yeah vanilla keeps your last read post, I was under the impression most forum software does that

-Brian

**Comment by akhoury** [comment]
does nodebb stores lastRreadPost Per topic? or is it just single value per each user?

**Comment by bdharrington7** [comment]
Last read post per topic

**Comment by akhoury** [comment]
thanks @bdharrington7
