### ISSUE TITLE
[IPB] Current selected exporter does not implement getMessages function

### ISSUE THREAD

**Issue by jacmoe** [akhoury/nodebb-plugin-import#141]
Why not ?

~~~
Error: ER_BAD_FIELD_ERROR: Unknown column 'ipb_topics.topic_answered_pid' in 'field list'
~~~

IPB 3

I had to set the prefix option to `ipb_` because it wouldn't run if I didn't - could not find "IPB_forums", etc..

I thought the ipboard importer was known to be working? :)

**Comment by akhoury** [comment]
Will take a look when I get home

**Comment by jacmoe** [comment]
I simply commented out line number 203 in nodebb-plugin-import-ipboard/index.js:
~~~
        var query = 'SELECT '
            + prefix + 'topics.tid as _tid, '
            + prefix + 'topics.starter_id as _uid, '
            + prefix + 'topics.forum_id as _cid, '
            + prefix + 'topics.topic_firstpost as _pid, '
            + prefix + 'topics.title as _title, '
            + prefix + 'topics.start_date as _timestamp, '
            + prefix + 'topics.views as _viewcount, '
            + prefix + 'topics.state as _status, '
            + prefix + 'topics.pinned as _pinned, '
            + prefix + 'topics.approved as _approved, '
            //+ prefix + 'topics.topic_answered_pid as _answerpid, '
            + prefix + 'posts.post as _content, '
            + prefix + 'posts.topic_id as _post_tid '
            + 'FROM ' + prefix + 'topics, ' + prefix + 'posts '
            + 'WHERE ' + prefix + 'topics.tid=' + prefix + 'posts.topic_id '
            + 'AND ' + prefix + 'posts.new_topic=1 '
            + (start >= 0 && limit >= 0 ? 'LIMIT ' + start + ',' + limit : '');
~~~

I have a rather big IPB3 database that I want to import - I am not sure if you have heard about Yii PHP Framework? ( yiiframework.com ) - I am in the process of trying to convince them to move to NodeBB :+1: 

Let me know if you need anything from me :)

**Comment by akhoury** [comment]
I've actually heard of Yii Framework, nice!

ok, i can help. The thing is, IPB keeps changing their database schema, hence these issues - and I can't keep up with forums changing schemas actually, there so many, but I will fix this one to the latest IPB schema if you have it. I could also implement the import-messages feature as well.

Would you be able to privately [email](mailto:bentael@gmail.com) me a database dump? I won't be able to help you without a look at the schema and its data - feel free to obfuscate emails, passwords and other sensitive data in it, or you can trust me with them if you want.

**Comment by jacmoe** [comment]
I succeeded in importing the messages - after commenting out that line :)
I will ftp the dump and email you the location - I am going to trust you with the data if you promise not to tell anyone :p

**Comment by jacmoe** [comment]
Let me know when you've downloaded it so that I can remove it. :)

Categories had parents but that wasn't taken into account after the import. Not a huge deal, though.

**Comment by akhoury** [comment]
What do you mean messages? private message are not supported yet.
also, i could probably fix the parent categories, most other plugins already supported, it's just that the IPB  one was written like a year ago, before I added many features to the core importer.

Also, delete the public link, I downloaded your DB dump

**Comment by jacmoe** [comment]
I meant posts, sorry :)

I did the conversion, but now it crashes in convert topics and posts:

~~~
controller.state { now: 'busy', event: 'controller.convertAll' }
controller.phase { phase: 'convertTopicsStart', data: undefined }
controller.progress { count: 0, total: 57777, percentage: 0 }
controller.progress { count: 1156, total: 57777, percentage: 2.000796164563754 }
controller.progress { count: 2312, total: 57777, percentage: 4.001592329127508 }
controller.progress { count: 3468, total: 57777, percentage: 6.002388493691261 }
controller.progress { count: 4624, total: 57777, percentage: 8.003184658255016 }
controller.progress { count: 5780, total: 57777, percentage: 10.003980822818768 }
11/12 04:49 [11059] - error: TypeError: Cannot read property 'implementation' of undefined
    at Function.getListeners (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:176:74)
    at Function.dispatch (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:192:40)
    at Object.events.EventTarget.dispatchEvent (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:287:33)
    at Object.DOMWindow.dispatchEvent (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:114:40)
    at /home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:50:16
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
TypeError: Cannot read property 'implementation' of undefined
    at Function.getListeners (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:176:74)
    at Function.dispatch (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:192:40)
    at Object.events.EventTarget.dispatchEvent (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:287:33)
    at Object.DOMWindow.dispatchEvent (/home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:114:40)
    at /home/jacmoe/webdev/nodebb/node_modules/nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:50:16
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
11/12 04:49 [11059] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
controller.progress { count: 1, total: 1, percentage: 100 }
controller.phase { phase: 'convertTopicsDone', data: undefined }
controller.phase { phase: 'convertDone', data: undefined }
controller.state { now: 'errored',
  event: 'controller.convertError',
  details: 
   { [MongoError: server 127.0.0.1:27017 sockets closed]
     name: 'MongoError',
     message: 'server 127.0.0.1:27017 sockets closed' } }
controller.progress { count: 6482, total: 57777, percentage: 11.218997178808177 }
~~~
I am using the html to markdown post process converter - it is not totally essential, although it looks weird when the forum is in markdown mode :)

Thanks for looking into this :)

**Comment by akhoury** [comment]
woah, that one is weird, 
will look into these issues, again, it has been really long since i test IPB migration

**Comment by akhoury** [comment]
all set, https://github.com/akhoury/nodebb-plugin-import-ipboard/commit/c7db1959ae96ca08b376f98f55a3bfd38e6c275d

rm the current nodebb-plugin-import-ipboard installed and update it.

I just imported your db, took about 1h30m, then i just the post-import tool to start and convert all HTML-TO-Markdown, that's probably gonna take another 30-60m. 

But you can give it a shot if you want.or I could send you the mongodb dump so you can take a look at it.

**Comment by jacmoe** [comment]
Really good news :+1: 
I am going to perform the import myself - thanks for the offer :) - I do need to get some mileage if I am to tell my local Yii framework server admin how it is to be done.

**Comment by akhoury** [comment]
oh, and I added support for private messages, as you might notice, because im nice

**Comment by jacmoe** [comment]
I'll let you know how nice you are, once I've performed the import - I am reinstalling NodeBB so I will probably let you know not until many hours has passed. :p
Thanks a lot! :)

**Comment by akhoury** [comment]
use NodeBB v0.9.1, not the latest

**Comment by akhoury** [comment]
the you can upgrade when you're ready, it's as easy as `./nodebb upgrade`

**Comment by jacmoe** [comment]
Just one quick question, if I may:
The posts are in html and using bbcode, should I perform the post-processing in two stages?
Or enable both html-2-markdown and bbcode converter?

**Comment by jacmoe** [comment]
I need the v0.9.2 for the new api endpoints, btw. (reply by email) - that is a feature that I want the new NodeBB powered forum to have (Discourse has it..)
Would it be okay to use the branch or should they install it by tag?

**Comment by akhoury** [comment]
bbcode-to-markdown will convert html also.

And 0.9.2 should be ok

**Comment by akhoury** [comment]
Just 
```
git checkout v0.9.2
```
