### ISSUE TITLE
GET https://storage.googleapis.com/code.getmdl.io/1.0.3/material.min.js 403

### ISSUE THREAD

**Issue by sohrabafard** [akhoury/nodebb-plugin-import#142]
in some location user can't get that js file, so they have this issue:

*Uncaught ReferenceError: componentHandler is not defined* :

`(anonymous function)	@	admin.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:20

w.event.dispatch	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:2

$event.dispatch	@	jquery.event.drag.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:374

y.handle	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:2

w.event.trigger	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:2

(anonymous function)	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:2

w.extend.each	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:1

w.fn.w.each	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:1

w.fn.extend.trigger	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:2

ajaxify.end	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:11

(anonymous function)	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:11

t.translate	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:13

(anonymous function)	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:11

f	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:10

(anonymous function)	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:10

$.ajax.success	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:11

u	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:1

f.fireWith	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:1

$	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:3

i	@	nodebb.min.js?v=09525b20-fd97-438c-8b10-ee18adbaad81:3`
.

**Comment by akhoury** [comment]
this is not an issue of this plugin, looks like you either have a connection trouble or https ,no idea.

https://github.com/NodeBB/NodeBB/blob/8787f0475749c66d1d004e8318d9b6d74cd46324/src/views/admin/header.tpl#L29
