### ISSUE TITLE
Toggle post-import tools Is disabled!

### ISSUE THREAD

**Issue by sohrabafard** [akhoury/nodebb-plugin-import#143]
*Pre-parse all content with my custom JavaScript*  and *Post-parse all content with my custom JavaScript* didn't show any input box when checked or unchecked them.

we have this errors on console on home page of this plugin : 

WebSocket connection to 'ws://forum.sanatisharif.ir/socket.io/?EIO=3&transport=websocket&sid=y503YP7m8nSQhawsAAAZ' failed: Establishing a tunnel via proxy server failed.

Uncaught Error: Load timeout for modules: settings,admin/modules/search,admin/plugins/import
http://requirejs.org/docs/errors.html#timeout

**Comment by sohrabafard** [comment]
LOAD TIMEOUT FOR MODULES: ...
§ 2
Likely causes and fixes:
There was a script error in one of the listed modules. If there is no script error in the browser's error console, and if you are using Firebug, try loading the page in another browser like Chrome or Safari. Sometimes script errors do not show up in Firebug.
The path configuration for a module is incorrect. Check the "Net" or "Network" tab in the browser's developer tools to see if there was a 404 for an URL that would map to the module name. Make sure the script file is in the right place. In some cases you may need to use the paths configuration to fix the URL resolution for the script.
The paths config was used to set two module IDs to the same file, and that file only has one anonymous module in it. If module IDs "something" and "lib/something" are both configured to point to the same "scripts/libs/something.js" file, and something.js only has one anonymous module in it, this kind of timeout error can occur. The fix is to make sure all module ID references use the same ID (either choose "something" or "lib/something" for all references), or use map config.

http://requirejs.org/docs/errors.html#timeout

**Comment by akhoury** [comment]
@sohrabafard some crashed the server, please provide server logs, not client.

**Comment by sohrabafard** [comment]
@akhoury nodebb in dev mod have this :

	12/12 19:52 [31206] - info: NodeBB Ready
	12/12 19:52 [31206] - info: Enabling 'trust proxy'
	12/12 19:52 [31206] - info: NodeBB is now listening on: 0.0.0.0:4567
	12/12 19:58 [31301] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.

	  * nodebb-plugin-blog-comments
	  * nodebb-plugin-dbsearch
	  * nodebb-plugin-recent-cards

	12/12 19:58 [31301] - info: [plugins/spam-be-gone] Settings loaded
	12/12 19:58 [31301] - info: NodeBB Ready
	12/12 19:58 [31301] - info: Enabling 'trust proxy'
	12/12 19:58 [31301] - info: NodeBB is now listening on: 0.0.0.0:4567
**Nginx logs are empty**

**Comment by sohrabafard** [comment]
this is my server configurations :
https://community.nodebb.org/topic/7219/nodebb-0-9-2-some-errors-route-websocket-uncaught-error-load-timeout-for-modules

Also I don't know what is " Enabling 'trust proxy'" in nodeBB logs.

**Comment by akhoury** [comment]
`trust proxy` is fine if your behind nginx. 
Did you actually complete the import process? or was it interrupted?

**Comment by sohrabafard** [comment]
when i install this plugin for first time, every thing was OK,
in progress of import break connection by restarting server,
 so I import database again with flush option,
After that I have this issue.

**Comment by sohrabafard** [comment]
something is wrong in log:

i watching dev log for long time, when i restart nodebb i see this:

    warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.

but i don't have redis, at the beginning i used redis, but i purge that and then install mongodb then import again ( It was here that the server be restarted and then did the operation again with flush option),
**So I don't have any redis in my server**

**Comment by sohrabafard** [comment]
I install redis-server , and import it's config in config.js so fix this issue,

I don't know why ? my nodebb use mongodb not redis database !!!

**Comment by akhoury** [comment]
usually if if the import was 
* incomplete
* reinstalled your node_modules after import
* or delete the Tmp files

this should fix it, create this file `lastimport` then restart nodebb and refresh the import admin page

```
cd /path/to/NodeBB
echo "1234567890" > node_modules/nodebb-plugin-import/server/tmp/lastimport
./nodebb restart

```

**Comment by sohrabafard** [comment]
thanks a lot
