### ISSUE TITLE
"MongoError: exception: E11000 duplicate key error index" during import

### ISSUE THREAD

**Issue by akhoury** [akhoury/nodebb-plugin-import#150]
```
[2016-01-08T23:28:23.017Z] [process-count-at: 7697] skipping post: 8912:tid:1011:_tid:1047:uid:76:_uid:77 MongoError: exception: E11000 duplicate key error index: 0.objects.$_key_1_value_-1 dup key: { : "topic:1011", : null }
```

**Comment by akhoury** [comment]
according to @barisusakli:

> it happens because we have a unique index on key_value, so it might be trying to insert the same key_value pair twice, im assuming this is running with something like `async.each()`
...
> drop the index by: `db.objects.dropIndex({_key:1, value: -1});`
...
> Comment these out
> https://github.com/NodeBB/NodeBB/blob/v0.9.2/src/database/mongo.js#L143-L147

**Comment by akhoury** [comment]
so  
1. kill nodebb 
2. comment these [3 lines](https://github.com/NodeBB/NodeBB/blob/v0.9.2/src/database/mongo.js#L143-L147) out, 
3. drop the index, using `db.objects.dropIndex({_key:1, value: -1});`
4. run nodebb 
5.import, 
6. when done, kill nodebb, 
7. uncomment, 
8. then run nodebb again to create the indices. 

@barisusakli any way I can disable the index programmatically without commenting lines of code out? what if I `db.dropIndex({_key:1, value: -1})` right before importing, that call would occur after the `ensureIndex` ones

**Comment by barisusakli** [comment]
Yes that should work.

**Comment by akhoury** [comment]
@barisusakli 

if I dropIndexes() and I comment out all the `objects` collection `ensureIndex(...)` (the 3 lines mentioned above, the import process slows down to halt, - if I only comment out the `{_key:1, value: -1}` index, still slow, but a little faster:

* no-changes: 7k users.import takes about __51 seconds__
* all objects indexes dropped: 7k users.import takes about __56 minutes!__
* only-`objects.$_key_1_value_-1` dropped: 7k users.import takes about __9 minutes__

I know that its impossible for you to debug this on the importer, but really, what is the underlying issue here? going back to what you said initially, 
> it happens because we have a unique index on key_value, so it might be trying to insert the same key_value pair twice, im assuming this is running with something like async.each()

Should I limit the import to 1 at a time? I guess I am trying to understand if it's importer issue or is it something with nodebb core? what I mean is, could this ever occur in a normal NodeBB usage? for example, say there is a "large" number of users trying to create many posts/topics at the same time.

**Comment by barisusakli** [comment]
Ahh I guess it is slower because functions like User.create() run db calls that use indices, without those each db call scans the entire collection.

I believe the issue is either 2 queries are running parallel that have the same key_value pair for example `topic:123 value:null` 

There is also a similar bug in mongodb at https://jira.mongodb.org/browse/SERVER-14322

I ran into this with an async.each trying to update the same document. So changing it to a async.eachSeries solved the problem in that case.

**Comment by barisusakli** [comment]
Is this happening during user import or posts? Maybe try switching to async.eachSeries() for the one causing it and see if it happens.

**Comment by akhoury** [comment]
> Is this happening during user import or posts?

The error occurs during posts and topics imports. But the slowing down, that just affects everything. 

I will try eachSeries thanks

**Comment by layernull** [comment]
I believe this issue can be closed. I had this error on 0.3.30 too, disappeared after the switch to eachSeries. Tested on numerous import runs.

**Comment by akhoury** [comment]
oh sweet, ok, feel free to reopen if you see it again.

**Comment by akhoury** [comment]
https://github.com/akhoury/nodebb-plugin-import/commit/ad59634b525ab7e3e3e9a57231c5b33e4e3b586f
