### ISSUE TITLE
Adding groups with the same name of an existing group causes issues

### ISSUE THREAD

**Issue by cp-nilly** [akhoury/nodebb-plugin-import#152]
Added ADMINISTRATORS group when the default Administrators group already existed. Showed up as two separate groups. When I deleted the ADMINISTRATORS group I get this error when I want to view the Administrator group.

![Error](http://i.imgur.com/lXBUh3K.png)

**Comment by akhoury** [comment]
yea you're right. Try to avoid adding that group, just add users with level "administrator"

**Comment by akhoury** [comment]
Actually, NodeBB should throw an error if the group has the same name.
https://github.com/NodeBB/NodeBB/blob/v0.9.2/src/groups/create.js#L24-L26

That actually should be a NodeBB bug, opened it here.
https://github.com/NodeBB/NodeBB/issues/4046
