### ISSUE TITLE
Messages are not post-processed

### ISSUE THREAD

**Issue by layernull** [akhoury/nodebb-plugin-import#158]
I am using 0.3.33 with NodeBB 0.9.2, importing from an old phpBB2. 
I believe I have found the following bug in 0.3.33:
Messages are imported and deleted but not post-processed. The message iterator and processing logic appears to be broken, imported message content is neither converted nor is the "_imported_content" key deleted when running the final "delete old records".

This is my final remaining import issue, would greatly appreciate any pointers to fix this to move on.

**Comment by akhoury** [comment]
I will look at that tonight.

On an unrelated note, which "exporter" are you using? 
this one? [nodebb-plugin-import-phpbb](https://www.npmjs.com/package/nodebb-plugin-import-phpbb), (src [here](https://github.com/psychobunny/nodebb-plugin-import-phpbb))

As far as I know, this is doesn't even support the `getPaginatedMessages()` function

**Comment by layernull** [comment]
Thank you! 

Yes, I am using nodebb-plugin-import-phpbb 0.1.5 exporter, which I modified to fit my phpbb2 database scheme (changed by PHP-Nuke) while adding the getPaginatedMessages() function by reusing and modifying code from this fork: https://github.com/belstgut/nodebb-plugin-import-phpbb

**Comment by akhoury** [comment]
actually I think found the bug, it's all related to the [`Data.keys()`](https://github.com/akhoury/nodebb-plugin-import/blob/master/server/data.js#L542-L559), which would affect the [email-confirmation code block](https://github.com/akhoury/nodebb-plugin-import/blob/master/server/importer.js#L915-L932)

Fixing in a few...

I am assuming you're using MongoDB right?

**Comment by akhoury** [comment]
> I figure out how to do so cleanly

there is no clean way right way, I am working on a refactor of this plugin, under the [/server/core](https://github.com/akhoury/nodebb-plugin-import/tree/master/server/core) directory, so all new clean work will go there, but it's not done yet.

**Comment by layernull** [comment]
Yeah, I am using MongoDB 3.2. Looking forward to your fix! I just now submitted my pull request for the extra data key deletion. Found a means to sync my fork so only the added lines show up.

**Comment by akhoury** [comment]
most of that commit is just tab fixes, here's the real changes

https://github.com/akhoury/nodebb-plugin-import/blob/a71b032066a6037dc2f3a6e8e53702f4720809a1/server/data.js#L547-L566

and

https://github.com/akhoury/nodebb-plugin-import/blob/a71b032066a6037dc2f3a6e8e53702f4720809a1/server/data.js#L261-L277

Messages are going to need a revamp with NodeBB 1.0 as Group Chat are now supported, that's on the [road map](https://github.com/akhoury/nodebb-plugin-import/issues/156) too to support within the importer as well.

**Comment by akhoury** [comment]
published 0.3.34 too.

**Comment by akhoury** [comment]
Thank you for this bug report, I would never actually caught that since I don't test Messages a lot.
