### ISSUE TITLE
Error on message import: "TypeError: Cannot read property 'timestamp' of undefined"

### ISSUE THREAD

**Issue by layernull** [akhoury/nodebb-plugin-import#160]
Sorry, to open another messaging related issue. 

Just tested the new 0.3.34 build to import messages. 

There now seems to be some sort of async collision, the slower I debug the code the more messages seem to get imported. Stacktrace start:
    
    14/1 00:47 [17392] - error: TypeError: Cannot read property 'timestamp' of undefined
        at [...]\NodeBB\src\messaging.js:245:75
        at fn ([...]\NodeBB\node_modules\async\lib\async.js:746:34
    
Caller / trigger is line 1065 in importer.js

     Messaging.addMessage(fromUser.uid, toUser.uid, message._content, onAddMessage);

**Comment by akhoury** [comment]
hmm ... and that didn't happen on 0.3.33 ?

**Comment by akhoury** [comment]
I am not able to reproduce this, but I've made some changes, that might fix it you. One thing I also recommend is try to order by timestamp.  see https://github.com/belstgut/nodebb-plugin-import-phpbb/pull/1

You'd need to either send me a copy of the dump you're working with OR debug it with me. Just just the latest master instead of the 0.3.34

**Comment by layernull** [comment]
I could successfully import messages up to 0.3.34 before.
However, I did now downgrade to 0.3.33 again, and now get the same error as on 0.3.34. Some build dependency must have changed.

I did now publish my own fork of the nodebb-plugin-import-phpbb where I already integrated the pull request you did on belstguts fork: https://github.com/layernull/nodebb-plugin-import-phpbb

I did also try your new master of nodebb-plugin-import. Unfortunately, when loading the app I get

    14/1 08:47 [10464] - error: Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([...]\NodeBB\node_modules\nodebb-plugin-import\server\index.js:3:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
14/1 08:47 [10464] - warn: [plugins] Unable to parse library for: nodebb-plugin-import

0.3.34 boots up fine.
.

**Comment by akhoury** [comment]
> `error: Error: Cannot find module 'fs-extra'`

if you're installing the master version, you need `npm install` its modules.

**Comment by layernull** [comment]
Yep, thanks. Got it to run, alas no joy, see updated comment. Still learning the ropes with Node.js app development. Great fun though.

**Comment by akhoury** [comment]
> I did now downgrade to 0.3.33 again, and now get the same error as on 0.3.34

I think your database is in a bad state. try to drop your mongo db and start fresh.
``` 
# 0 being the name of the default database, you could have called it something else, see your config.json

mongo 0 --eval "db.dropDatabase()"
./nodebb --setup # set up a fresh nodebb database again
```

**Comment by akhoury** [comment]
> see updated comment

I don't understand, I cannot see what got updated, can you strikethrough what's not valid anymore in your comment?

**Comment by layernull** [comment]
Sorry for any confusion! I did mention my updated comment because I had fixed and removed my problems with a 'fs-extra' a number of hours before you posted the fix. 

Will test with a fresh mongoDB schema next.

**Comment by layernull** [comment]
I can confirm the TypeError disappeared with a fresh mongoDB setup!
This is rather worrisome, since I don't know what went wrong, so I am not sure how to prevent this from happening again. 

Now everything seems to work, except for email auto confirmation. The "email:confirm" keys are still missing in the user objects. My old quick fix for this now fails, too.

**Comment by akhoury** [comment]
> This is rather worrisome, since I don't know what went wrong, so I am not sure how to prevent this from happening again.

You're right, but i suspect that you had bad messages objects in there due to the messages bug you filed earlier.

> The "email:confirm" keys are still missing in the user objects.

you mean `email:confirmed`? I think NodeBB changed the schema since I wrote that part. try it now against master.

**Comment by layernull** [comment]
I put my hot fix in the wrong file... 
Yeah I mean "email:confirmed". The current master now sets the value, however it sets 0 instead of 1.

**Comment by akhoury** [comment]
Ah, ok, i gtg run somewhere, will fix it when I get back.

**Comment by layernull** [comment]
No worries, the hotfix / workaround is easy, just replace

    'email:confirmed': config.autoConfirmEmails ? 1 : 0,

with 

    'email:confirmed': 1

**Comment by akhoury** [comment]
that should take care of the emails confirm checkbox value being false all the time.

https://github.com/akhoury/nodebb-plugin-import/commit/58b7a0ae5752792052f13654b81c0841231b7255

**Comment by layernull** [comment]
Fix looks good, thank you!

**Comment by akhoury** [comment]
no worries.

**Comment by layernull** [comment]
I did re-import today, I can confirm the fix.

**Comment by akhoury** [comment]
thanks
