### ISSUE TITLE
Pinned Topics not sorted properly?

### ISSUE THREAD

**Issue by cp-nilly** [akhoury/nodebb-plugin-import#161]
Not sure if this is a problem with the import plugin or not. After making use of the _pinned field for topics, I've noticed that the pinned topics were not placed at the top of the selected category as one would expect. In order to resolve the issue one would need to find each pinned topic, unpin it and then re-pin it.

**Comment by akhoury** [comment]
aha, i see. I think i know why.

**Comment by Armadill0** [comment]
This has not solved the problem for me.

While the import runs, the topics are sorted correctly, but when the import has ended they are being sorted like normal topics. Maybe this has something to do with the fixTimestamps for topics afterwards or any other post import script?

**Comment by akhoury** [comment]
@Armadill0 are u using exactly `NodeBB@1.0.0`

**Comment by Armadill0** [comment]
@akhoury Yes NodeBB 1.0.0 with latest Import Plugin 0.3.42.
