### ISSUE TITLE
Creation order of topic and posts

### ISSUE THREAD

**Issue by layernull** [akhoury/nodebb-plugin-import#163]
Question:

Normally topic_id, post_id and timestamp are aligned, so it does not matter in which order the import occurs.

Because of migration, unfortunately I have a state in my old forum where the correct order for recent post would be by timestamp, not by post_id or topic_id. It is easy to fix the timestamp, hard/impossible to fix the id in the DB.

I did try to get a correct recent order in NodeBB by adding "Order By" statements to both getPaginatedPosts and getPaginatedTopics by timestamp in the exporter.

Alas, this did not have any effect on the ordering of the topics and posts created in NodeBB by the importer. It is still ordered by topic_id or post_id of the old forum.

If there is a simple code change to sorting by timestamp instead of id during import without breaking everything, I would be very curious.

If there isn't just say so and close this issue as won't fix or something. 

Thanks!

**Comment by akhoury** [comment]
i dont understand the problem? why do you care which order the posts get created by?

and to answer your question, i think there is a way to force the order...

**Comment by akhoury** [comment]
oops closed by mistake, 

see this https://github.com/layernull/nodebb-plugin-import-phpbb/pull/1

**Comment by akhoury** [comment]
but still want to know why do you care about the order.

**Comment by layernull** [comment]
Yeah I know strange request, I will try your array hack and report back. Thank you for that in any case!

The reason why I want to try this, is the following:

On my old page I have forums and a basic blogging engine. I didn't use the blogging part much, so I decided to give that up when migrating to NodeBB. To not lose content of the few articles I made, I reposted them as new topics in the old forum. Some of those articles were pretty old, so I fixed the timestamps of both topic and post to reflect the original article date.

My old site has a "recent post" module on the front page which sorts the most recent posts by post_id, ignoring the timestamp. 

NodeBB acts exactly the same way. So my old articles pop up in the very front, even though they should not.

If all posts / topics were imported by order of timestamp and not old topic / post id this might fix this weird issue.

It is a very minor problem, but still...

**Comment by akhoury** [comment]
oh, sound like a NodeBB bug OR the importer is not creating the right sortedSet. 

See NodeBB doesn't just use the timestamp on `post:1234` hash, but for efficiency reasons, they create another sortedSet - they do that for many many sets and I try to update them all with the new timestamps, if you're seeing this issue, then I may have missed something. You shouldn't need to do all that work, timestamps are the way to go.

Let me take a look, will do that tonight.

**Comment by layernull** [comment]
Cool, thanks for taking a look in advance. :)

**Comment by layernull** [comment]
I just tested your array pull request, thanks! It does finish through without errors but as expected does not fix this issue, because it is likely associated with some not correctly sorted set.

I also tried manipulating the tid of a post with a recent timestamp to move it up front on the recent post widget to no avail. Only messed up stuff did not "move" the post.

**Comment by akhoury** [comment]
give it a shot now.

**Comment by layernull** [comment]
Yes, this fixed my issue! :+1: Both recent topics and recent posts now behave as expected sorted by timestamp.
Thank you!
