### ISSUE TITLE
Best forum to import from?

### ISSUE THREAD

**Issue by CarlosRodriguez1982** [akhoury/nodebb-plugin-import#178]
I have a SMF forum and I have tried SMF and MyBB forum importers but none of them seems to import private messages. What is the recommended forum to import from so I can import from SMF to that forum and then to NodeBB?

I believe this plugin was created for UBB but now that software is not free anymore.

It would be great if link conversion is also included so I don't have to do it manually.

Thanks.

**Comment by akhoury** [comment]
so you're original forum is an SMF forum? why not add support for private messages?

file a ticket here, i'll add it when i get a chance.
https://github.com/a5mith/nodebb-plugin-import-smf

**Comment by CarlosRodriguez1982** [comment]
Yes the original is SMF.

Thanks a lot.
