### ISSUE TITLE
Invalid html crashes post-parsing of data

### ISSUE THREAD

**Issue by bdharrington7** [akhoury/nodebb-plugin-import#179]
I tried converting on my DO droplet tonight, and one of the posts caused the process to crash. I'm not sure where to fix the error, I just got this error:

```
8/3 03:00 [10791] - error: DOMException: Invalid character: "href"http:" did not match the Name production: Expected "-", ".", ":", "\xB7", "_", [0-9], [A-Z], [\u0300-\u036F], [\u0370-\u037D], [\u037F-\u1FFF], [\u200C-\u200D], [\u203F-\u2040], [\u2070-\u218F], [\u2C00-\u2FEF], [\u3001-\uD7FF], [\uD800-\uDB7F], [\uF900-\uFDCF], [\uFDF0-\uFFFD], [\xC0-\xD6], [\xD8-\xF6], [\xF8-\u02FF], [a-z] or end of input but "\"" found.
    at exports.name (.../nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/to-markdown/node_modules/jsdom/lib/jsdom/living/helpers/validate-names.js:10:11)
 ....
```

some more forgiving error handling should happen, or it should point to the offending post somehow

**Comment by akhoury** [comment]
hmm .. well, if it fails.. i think i should throw a warning and don't convert the post, is that Ok you think?

**Comment by bdharrington7** [comment]
I think that would be more appropriate. An output of the problematic post
content and id would be even more helpful
