### ISSUE TITLE
Access Denied for 'root'@'localhost'

### ISSUE THREAD

**Issue by perarg** [akhoury/nodebb-plugin-import#180]
Hello, i have an access denied error when trying to import data to NodeBB. I got the following error:
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

But if i try from terminal with the following command:
`mysql -u root -p` and enter the password i get in mysql....

**Comment by nhlpl** [comment]
Wrong port number?
http://stackoverflow.com/a/17957132

**Comment by akhoury** [comment]
3306 is the default. Does nodebb live on a different machine than the one mysql lives on? 
you could have remote access turned off, especially for `root`

**Comment by perarg** [comment]
No it is on same machine and default port (3306).

**Comment by nhlpl** [comment]
Please try to add a new user to this database. I think root access can be limited just to CLI.

**Comment by akhoury** [comment]
are u on windows by any chance ?

**Comment by perarg** [comment]
@nhlpl I will try that later and update the post
@akhoury No i have tried it only on my mac. I will try @nhlpl idea and if not maybe i will try it into a windows machine

**Comment by akhoury** [comment]
no no, it's not the windows thing, I was just asking because windows is sometimes weird about the local host name, I'm on a mac too, what happens if you create a simple test case

```javascript
var mysql = require('mysql');

var connection = mysql.createConnection({
    host: 'localhost', // you can also try '127.0.0.1'
    port: 3306,
    user: 'root',
    password : 'password', 
    database : 'my_database'
});
connection.query("SELECT 1", function(err) {
    if (err) console.error("NOT-OK", err);

    console.log("OK")
});
```
then
```
# if you haven't installed that module in your working directory
npm install mysql 

node tmp.js
```

**Comment by perarg** [comment]
@akhoury test it and update this :) Thanks for the rapid reply

**Comment by akhoury** [comment]
wait what was the problem?

**Comment by perarg** [comment]
the problem described on the first post. Access Denied Error instead of typing the correct credentials.

**Comment by akhoury** [comment]
you said:
> test it and update this :) Thanks for the rapid reply

what did you update? i'm confused, you're first post is the same. Did you just have the wrong credentials entered? can we close this issue?

**Comment by perarg** [comment]
Sorry, bad english. I meant that i **will** try making your suggestion @akhoury of **tmp.js** file and i will tell you here the results :)

**Comment by perarg** [comment]
> what happens if you create a simple test case

I tried @akhoury test scenario and i have a successful login to the database with OK statement.

But still get denied message in plugin interface
![screen shot 2016-03-23 at 12 05 06](https://cloud.githubusercontent.com/assets/1533511/13981927/b4b59e3e-f0ef-11e5-9f27-796d8e04751b.png)

**Comment by akhoury** [comment]
Are u by any chance typing the wrong password in the importer's config? :P CapsLock on? i know that sounds ridiculous, but I can't think of anything else.

or you know, which exporter-plugin are you using? vanilla? vbulletin? etc...

**Comment by perarg** [comment]
I have double checked typing, no I am afraid the password password is correct...
I use vbulletin

**Comment by akhoury** [comment]
im not sure i can help you much here without some sort of remote access to your machine, if you want to, send me an email, here bentael@gmail.com

**Comment by Fidelix** [comment]
I can help you debug this problem too.
akhoury already has a lot of stuff on his plate.

You could try to write some console.log statements in the code and check the output in nodebb's log.

**Comment by akhoury** [comment]
hey @Fidelix thanks for this, we already had a remote access session and ruled out that it was that a [VB exporter](https://github.com/akhoury/nodebb-plugin-import-vbulletin) issue, it doesn't support VB5 yet.

**Comment by perarg** [comment]
Thank you @Fidelix for your willingness! @akhoury has resolved my issue and i appreciate his help for that :+1:

**Comment by akhoury** [comment]
https://github.com/akhoury/nodebb-plugin-import-vbulletin/issues/6
