### ISSUE TITLE
NodeBB version support

### ISSUE THREAD

**Issue by codecowboy** [akhoury/nodebb-plugin-import#181]
I noticed that my admin panel on my test machine is asking me to upgrade to nodeBB v.1.0.x. There's a note in the docs in this repo saying that it isnt supported on 0.9.3 and above. Is that still the case? I'm just asking because sometimes github project docs are not up to date ;)

I have 0.9.0 sitting on a server (not live). I have 0.9.3 on my test machine. I need to run an importer in my local environment to test it and then again on the server, eventually putting the forum live.

Is 1.0 even stable? And would you recommend putting both environments on 0.9.2 ? I'll be importing from punBB.

**Comment by akhoury** [comment]
umm  so as of today, this plugin ONLY supports NodeBB 0.9.2 - however, I have plans to merge this PR https://github.com/akhoury/nodebb-plugin-import/pull/177 along with few other changes, in the next few weeks (maybe sooner) to up the support to NodeBB 1.0 with support of the chat-rooms feature,

**Comment by akhoury** [comment]
nodebb-plugin-import@0.3.41 now support NodeBB v1.0.0
