### ISSUE TITLE
Passwords missing

### ISSUE THREAD

**Issue by codecowboy** [akhoury/nodebb-plugin-import#182]
I ran an importer (punbb2) and the users don't seem to have any password field in the DB (Mongo). The docs say:

> 
 ...which is just list of of all of the imported users, emails, oldId, newId, joindateTimeStamp, and most importantly, their new passwords (if you have configured the importer to generate passwords for you - i highly recommend against that, let them reset their passwords).

In the importer there is an option to just set the passwords to null but I seem to have no password at all rather than a password field with a null value.

If I do a mongo query :` { "password": { $exists: true } }
`
Only the Administrator I setup when I installed NodeBB is returned.

I selected the option to download a user.csv and saw:

> 
> [2016-03-24T08:09:43.599Z] current phase: usersCsvDone (time since previous phase: 5s)
> 
> [2016-03-24T08:09:38.510Z] current phase: usersCsvStart

But nothing downloads? Is this stored on the server somewhere? Ultimately I just need a way for migrated users to log in and be prompted to reset their passwords

**Comment by akhoury** [comment]
are u checking this box? "Auto Password Generation" once you do, each user will get a random password generated for them. 
![screen shot 2016-03-24 at 9 40 09 am](https://cloud.githubusercontent.com/assets/1398375/14018496/7a4860be-f1a4-11e5-87ff-b58c5e0ebcc6.png)

however, I do recommend against that because now you have email them these password as clear text, which is not safe.

**Comment by codecowboy** [comment]
No, I am not checking that box

**Comment by akhoury** [comment]
also, no password field is like a null password in mongo, which just means the use cannot login, he/she would need to reset their passwords.

**Comment by codecowboy** [comment]
How would they reset their password if they follow the lost password
procedure? I cant seem to test this as I get an Invalid email error. V
frustrating :(

**Comment by akhoury** [comment]
you should be able to click on forgot password and receive a reset-link to your email.
paste the error logs for the invalid email please.

Also, you need to have an emailer plugin setup to be able to send an email.

**Comment by codecowboy** [comment]
Thanks - see this issue also
https://community.nodebb.org/topic/8366/invalid-email-error-when-trying-to-reset-password
.

Will test this when I can.

On Thursday, 24 March 2016, Aziz Khoury <notifications@github.com> wrote:

> you should be able to click on forgot password and receive a reset-link to
> your email.
> paste the error logs for the invalid email please.
>
> Also, you need to have an emailer plugin setup to be able to send an email.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/akhoury/nodebb-plugin-import/issues/182#issuecomment-200906306>
>


-- 
Sent from Gmail Mobile

**Comment by codecowboy** [comment]
@akhoury I've tested this with the Mailgun email plugin. Nothing shows up in the logs. Is there some way I can increase the log verbosity?

**Comment by akhoury** [comment]
```
NODE_ENV=development ./nodebb start
./nodebb log
```

**Comment by codecowboy** [comment]
thanks - still nothing in the logs. It sent an email for the administrator user so I guess I broke something by editing the DB manually.

**Comment by bdharrington7** [comment]
If this is still an issue, I noticed in this plugin the option to save the generated password is actually commented out, you'd have to uncomment it to actually save / export any generated passwords. Like @akhoury says it might be a security concern, so sending out the password reset through NodeBB would be the best course of action

**Comment by akhoury** [comment]
there is still the option of implementing your own sign-on logic against the old-forum-database, but that would be a case by case scenario and it's out of the scope of this project.
