### ISSUE TITLE
Heading spaces of posts are removed after import.

### ISSUE THREAD

**Issue by xidui** [akhoury/nodebb-plugin-import#195]
I found in source code:
```
topic._content = (topic._content || '').trim();
```
Why `trim` it? 

Actually, in some of my old posts there are some heading spaces which will be used for Markdown view. But after imported, the heading space is removed by `trim` which results that the Markdown content not show properly.

**Comment by akhoury** [comment]
good point, ill remove it, or feel free to submit a PR
