### ISSUE TITLE
getPaginatedMessages doesn't work with touid anymore

### ISSUE THREAD

**Issue by Armadill0** [akhoury/nodebb-plugin-import#208]
Hi,

sorry to bother you with another issue, but since some version between 0.3.32 and 0.3.36, the message import with only the touid instead of the roomId doesn't work anymore. I tried all versions from 0.3.29 to 0.3.42 found none which worked for me. 
As there were many changes because of the Rooms it's very hard for me to find out what the exact problem is about. But it seems it always tries to use the roomId wether it is defined or not:

> [2016-09-07T21:09:18.446Z] [process-count-at: 2987] skipping message:_mid: 13663 _fromuid:5:imported: true, _roomId:undefined:imported: true err: [[error:chat-room-does-not-exist]]
> [2016-09-07T21:09:18.444Z] [process-count-at: 2986] skipping message:_mid: 13662 _fromuid:8:imported: true, _roomId:undefined:imported: true err: [[error:chat-room-does-not-exist]]
> [2016-09-07T21:09:18.441Z] [process-count-at: 2985] skipping message:_mid: 13661 _fromuid:5:imported: true, _roomId:undefined:imported: true err: [[error:chat-room-does-not-exist]]
> [2016-09-07T21:09:18.438Z] [process-count-at: 2984] skipping message:_mid: 13660 _fromuid:8:imported: true, _roomId:undefined:imported: true err: [[error:chat-room-does-not-exist]]
> [2016-09-07T21:09:18.436Z] [process-count-at: 2983] skipping message:_mid: 13659 _fromuid:64:imported: true, _roomId:undefined:imported: true err: [[error:chat-room-does-not-exist]]
> [2016-09-07T21:09:18.431Z] [process-count-at: 2982] skipping message:_mid: 13658 _fromuid:5:imported: true, _roomId:undefined:imported: true err: [[error:chat-room-does-not-exist]]

Can you have a look into that? As I currently have no good idea how to realize Rooms for phpbb imports (handling multi-target messages is not trivial) it would be quite handy if the fallback method without Rooms could still be used.

**Comment by akhoury** [comment]
https://github.com/psychobunny/nodebb-plugin-import-phpbb/issues/7
