### ISSUE TITLE
Import plugin crashes every time I try to migrate from vBulletin to nodebb

### ISSUE THREAD

**Issue by cetkoprodanovic** [akhoury/nodebb-plugin-import#210]
I am using import plugin to migrate from vBulletin 4.2.2. Importer crashes every time I try. This is how it is looks like. It is same every time.
Can anyone help me?

https://i.imgur.com/vN7x91D.png

**Comment by akhoury** [comment]
do you have the server logs?

**Comment by akhoury** [comment]
also, are you using Nodebb v1.0.0

**Comment by cetkoprodanovic** [comment]
Thank you. But we solved it. It was about vbulletinn dataabse data inconsitancy.
