### ISSUE TITLE
Cannot read property 'get' of undefined acp.js.270

### ISSUE THREAD

**Issue by krombox** [akhoury/nodebb-plugin-import#213]
Good day. I am trying to use this plugin and import data from old forum.

I am facing an issue when i click **Don't Flush NodeBB DB, just import** and **Flush NodeBB DB, then import**. The problem is nothing happened. On console i see an error  `Uncaught TypeError: Cannot read property 'get' of undefined` on acp.js:270 line

`
				$.ajax({
					type: 'post',
					data: {
						_csrf: csrf.get(),
						config: config
					},`

NodeBB version v1.2.1
I tried to console.log(csrf) and it is undefined. Could someone help with this?

**Comment by bdharrington7** [comment]
Did you read the readme

**Comment by krombox** [comment]
Did i missed something?

> LATEST VERSION ONLY SUPPORTS
seams i am using latest.

**Comment by bdharrington7** [comment]
You have to go to the next line:

> LATEST VERSION ONLY SUPPORTS:
> NodeBB v1.0.0

**Comment by krombox** [comment]
Sorry, my fault. For some reason after text `LATEST VERSION ONLY SUPPORTS` i though that plugin could be used on any version >= v.1.0.0, but not just 1.0.0 . 
Plugin works well. Good job.

Thanks for your help.
