### ISSUE TITLE
[exporter] nodebb-plugin-import-kunena

### ISSUE THREAD

**Issue by Couby** [akhoury/nodebb-plugin-import#216]
Hi,

Trying to port a Kunena forum to Nodebb (veaf.org/fr/forums -> community.veaf.org).

I tried https://github.com/eyesofkids/nodebb-plugin-import-kunena .

Looks not too far from the goal :blush: .

Users and categories import looks good.
Just a lot of topics and messages missing...

The log (minus repetitive errors for topics and messages import) : 
[logs.txt](https://github.com/akhoury/nodebb-plugin-import/files/966435/logs.txt)

Maybe the problem is with topics import and the related error **error:user-too-new** ?

Regards

**Comment by akhoury** [comment]
are you still having issues? sorry for the delay on this one. Closing since it's too old but feel free to reopen
