### ISSUE TITLE
Error: connect ENOENT /Applications/MAMP/tmp/mysql/mysql.sock

### ISSUE THREAD

**Issue by andreapernici** [akhoury/nodebb-plugin-import#217]
When starting the importer we get the following

`Error: connect ENOENT /Applications/MAMP/tmp/mysql/mysql.sock`

but we don't use MAMP and we don't have those path. Why this is prompting?

**Comment by akhoury** [comment]
oh, which exporter are u using?

**Comment by t0rched** [comment]
Alias this file to your actual Linux socket file. Mine was /var/run/mysqld/mysqld.sock.  You will have to do something  like...
`mkdir /Applications
mkdir /Applications/MAMP
....
ln -s /var/run/mysqld/mysqld.sock mysql.sock`

**Comment by akhoury** [comment]
thanks @KipperedSnack

**Comment by juan-g** [comment]
This happens with nodebb-plugin-import-vbulletin because of the socketPath line:
```
// mysql db only config
// extract them from the configs passed by the nodebb-plugin-import adapter
var _config = {
	host: config.dbhost || config.host || 'localhost',
	user: config.dbuser || config.user || 'user',
	password: config.dbpass || config.pass || config.password || undefined,
	port: config.dbport || config.port || 3306,
	database: config.dbname || config.name || config.database || 'vb',
	socketPath: '/Applications/MAMP/tmp/mysql/mysql.sock'

};
```
The line is active when installing today by `npm install nodebb-plugin-import-vbulletin` (from the _nodebb_ folder). However, it's commented out on the GitHub version:
```
//, socketPath: '/Applications/MAMP/tmp/mysql/mysql.sock'
```
(See https://github.com/akhoury/nodebb-plugin-import-vbulletin/blob/master/index.js)

**Comment by akhoury** [comment]
ah i need to publish it then

**Comment by akhoury** [comment]
published
