### ISSUE TITLE
NodeBB 1.0.3 is Broken

### ISSUE THREAD

**Issue by KipperedSnack** [akhoury/nodebb-plugin-import#219]
NodeBB 1.0.3 is broken with me... incurable CSRF errors... so... am I just SOL on getting this installed?

**Comment by t0rched** [comment]
Fixed. Appears they recommend upgrade to fix it, but you can simply do this after using npm install:
`cp node_modules/socket.io-client/dist/socket.io.js node_modules/socket.io-client/`

HOWEVER, now I am kinda just stuck at the plugin screen for import. I have configured both sections... yet it doesn't seem to do or log anything...

**Comment by t0rched** [comment]
It worked, then failed on some usergrouprank check thing... i disabled a few lines in the code and then re-ran after setting some of the checks to "true". 

Worked. This bypassed whatever was continuing/halting the process, and then I was able to run the convert.

**Comment by akhoury** [comment]
i upped the support to 1.7.5, this issue should have been resolved now
