### ISSUE TITLE
Some special characters not supported? Polish MyBB import

### ISSUE THREAD

**Issue by Vioner** [akhoury/nodebb-plugin-import#224]
**I'm following the readme guide of the importer, but the special characters keep importing as:**

> **�** 
> U+FFFD - REPLACEMENT CHARACTER used to replace an unknown, unrecognized or unrepresentable character

Example post:

![image](https://user-images.githubusercontent.com/7596867/46820187-dd2f2900-cd85-11e8-8022-fae4c7d65ce1.png)

Of course I'm following the readme guide of the importer. 
Exporter used: https://github.com/ASCIIcat/nodebb-plugin-import-mybb
 
I've tried converting to different encoding before import, but it didn't help. 
After seeing #108 I assumed that the problem is on the mybb importer side... Hm
I didn't find any code relating to charset/encoding there so I'm back here. 
Maybe the myBB exporter is incompatible with current main plugin?
Later, I'll setup a different forum engine where I'll use Polish characters and then try to import.

I'm hoping you can help me get this to work properly @akhoury 
@ASCIIcat if you're still active, maybe you can also help.

If this is on the mybb exporter side, let me know and I'll try to write my own version.
Thanks

**Comment by Vioner** [comment]
I've just checked the SMF exporter on a fresh SMF installation. 
Polish characters unsupported - same problem. 

Since the SMF exporter is the most recently done, I'm assuming the problem is on the importer plugin side.

**Comment by akhoury** [comment]
are you using a `parseBefore` setting? if so, can i see it the code block?

**Comment by Vioner** [comment]
I'm not using it. My data is in UTF-8 so it shouldn't be needed. I've also verified the validity of the strings in database, and everything is fully valid, so the black question mark diamonds aren't my fault :/

**Comment by Vioner** [comment]
I've solved the problem @akhoury 
I'll share the fix and findings ASAP, but I'm informing you now so you wouldn't waste your time ;)

**Comment by akhoury** [comment]
good to know ! thanks for sharing !
