### ISSUE TITLE
Failed to lookup view "admin/plugins/import"

### ISSUE THREAD

**Issue by sheganinans** [akhoury/nodebb-plugin-import#234]
So, I've tried quite a few things. I disabled all the plugins, restarted the nodebb server, still getting this error.

NodeBB version: 1.12.1
Node version: 10.18.1
NPM version: 6.13.4
Ubuntu 18.04
Mongo 4.0.15

I also nuked the the NodeBB install by deleting the directory a few times, including dropping all the collections in Mongo. Maybe I'm not clearing everything away?

**Comment by akhoury** [comment]
hmm, can you try `./nodebb build` after you've installed and activated the import plugin?

**Comment by sheganinans** [comment]
Perfect! That worked! 

Maybe, just to be careful, consider adding a little something to the README to avoid this issue?

**Comment by akhoury** [comment]
Done! thanks for reporting.

**Comment by GamerGirlandCo** [comment]
this is still an issue for me :(

> NodeBB 1.12.1
> Node 12.16.2
> NPM 6.14.9
> MongoDB 4.4
> Windows 10 build 19041.685

help?

**Comment by akhoury** [comment]
@GamerGirlandCo got any error logs? anything?

**Comment by oliverpechey** [comment]
Can confirm a rebuild fixed my issue. Thanks!
