### ISSUE TITLE
are nested categories supported during import from vbulletin

### ISSUE THREAD

**Issue by reshadi** [akhoury/nodebb-plugin-import#236]
Hello,
thank you for your free tool for importing Vbulletin. This seems to be the only option available.

I'm trying to import a fairly large vb 4.2.5 forum (300k users, 2M posts, 130k topics) with rather large and heavily nested & hierarchical forum structure.
I know that at least latest NodeBB supports nested categories.

I managed to setup the old 1.12.1 nodebb and start the import. After 2 days into the import, it is still going on, but I have noticed that the imported categories in the new nodebb forum are all flat!

Are the hierarchical categories supported in the importer?

I'm not sure if this repository still supported, but I thought I give it a try.

Thanks.

**Comment by akhoury** [comment]
Hi sorry for the really late reply here. To answer your question, yes, nested categories are supported using the `_parentCid` property

https://github.com/akhoury/nodebb-plugin-import/blob/master/write-my-own-exporter.md#yourmodulegetpaginatedcategoriesstart-limit-callback-required-function
