### ISSUE TITLE
[exporter] PunBB

### ISSUE THREAD

**Issue by akhoury** [akhoury/nodebb-plugin-import#32]
https://github.com/patricksebastien/nodebb-plugin-import-punbb/issues/1

**Comment by codecowboy** [comment]
I could provide a punBB dump if required. I am interested in importing from punbb. I've just installed nodebb so have version 0.80. Will the importer work with this version? 0.7 is mentioned in the readme.

**Comment by akhoury** [comment]
sure - email it to me.
I would probably need to publish like a new npm module, nodebb-plugin-import-punbb2 to use my [fork](https://github.com/akhoury/nodebb-plugin-import-punbb) from [patricksebastien's fork](https://github.com/patricksebastien/nodebb-plugin-import-punbb/pull/2)
btw - The importer now works with the latest stable NodeBB v0.8.2,

**Comment by akhoury** [comment]
ugh - email/share it to bentael@gmail.com

**Comment by codecowboy** [comment]
@akhoury  Will do - haven't worked on this in a while but it is being resurrected. Thanks!

**Comment by codecowboy** [comment]
@akhoury I've emailed you the dump file. Apologies for the delay.

**Comment by akhoury** [comment]
got it, I will test as soon as i can, probably another week from now.

**Comment by codecowboy** [comment]
Cool. In the meantime, can you confirm if I can try this via the Node Admin panel or if I need to try an import from the command line as was detailed here - http://www.workinprogress.ca/punbb-to-nodebb

**Comment by codecowboy** [comment]
See also https://github.com/patricksebastien/nodebb-plugin-import-punbb/issues/3

**Comment by akhoury** [comment]
you should try my fork, https://github.com/akhoury/nodebb-plugin-import-punbb 
not patricksebastien's

I submitted PR to him more than a year ago, he doesn't seem responsive 
https://github.com/patricksebastien/nodebb-plugin-import-punbb/pull/2 

In the Admin Panel > Import > Pre-Import Config > Select an Exporter
don't select one from the select box, just modify the text input below and enter
 `git://github.com/akhoury/nodebb-plugin-import-punbb#master`

to install mine copy.

Or, you can

```
cd nodebb/node_modules
git clone https://github.com/akhoury/nodebb-plugin-import-punbb
cd nodebb-plugin-import-punbb
npm install
cd ..
node app
```

Then from the admin panel, select exporter, same select box, just type `nodebb-plugin-import-punbb` and make sure you select the "Skip Module Install" box.

but anyways, there're probably few bugs in it anyways, since I just wrote my fork from memory, i didn't have a punbb dump - so.. i would wait till i confirm it's all good or if you're feeling lucky and want to fix it.

**Comment by akhoury** [comment]
@codecowboy - tested and published - looks good so far.

Once you install "" and activate "nodebb-plugin-import", open the Pre-Import Settings > Select Exporter, but you're not gonna find "nodebb-plugin-import-punbb2" in the select box, just type `nodebb-plugin-import-punbb2`  in the text box below, __notice I added "2" at the end__

i will add it to the select box on my next nodebb-plugin-import release.

But you don't have to "Skip the Module Install" anymore (unless you npm install it yourself), it's published to [npm](https://www.npmjs.com/package/nodebb-plugin-import-punbb2) so that should work.
 
### Screenshot of my exporter settings

<img width="1333" alt="screen shot 2015-11-18 at 11 52 50 pm" src="https://cloud.githubusercontent.com/assets/1398375/11263130/8438baa4-8e55-11e5-9d68-702ecf0a21d0.png">
