### ISSUE TITLE
[exporter] MyBB

### ISSUE THREAD

**Issue by akhoury** [akhoury/nodebb-plugin-import#35]
need a dump

**Comment by Radiergummi** [comment]
May I ask what the status of this exporter is?

**Comment by ASCIIcat** [comment]
The exporter has not been updated to the latest version of nodebb but should still be in a working state. Have recently used it to migrate a forum over

**Comment by akhoury** [comment]
https://github.com/ASCIIcat/nodebb-plugin-import-mybb

**Comment by akhoury** [comment]
@Radiergummi 

install the correct version of NodeBB, read this here

https://github.com/akhoury/nodebb-plugin-import#works-with-nodebb-v06x-last-tested-against-37235557bba1a582dfd845aea13d4ca22ffcc746
