### ISSUE TITLE
[exporter] Vanilla

### ISSUE THREAD

**Issue by fr3em1nd** [akhoury/nodebb-plugin-import#94]
thank you!!

**Comment by kerphi** [comment]
Please prioritize this request. A vanillaforum to nodebb script would be great !

**Comment by phoenixlzx** [comment]
Any update?

I'm seeking for a plugin to migrate from Vanilla as well. Thanks.

**Comment by bdharrington7** [comment]
I've got most of the development for one [here](https://github.com/bdharrington7/nodebb-plugin-import-vanilla/tree/d147bb121e367f62d367560106c1fbbf1c7eb019) but it's a work in progress.. There are some missing things like a user's place in the thread (because NodeBB [doesn't support it yet](https://github.com/NodeBB/NodeBB/issues/1064))

However some plugins (like quotes and spoilers) are supported.

**Comment by akhoury** [comment]
nice work @bdharrington7  - let me know if there is anything i can help with
also let me know when you have a stable release so I can add it to the supported [list](https://github.com/akhoury/nodebb-plugin-import/blob/master/package.json#L52)

**Comment by phoenixlzx** [comment]
@bdharrington7 Thanks, I tried it and it works mostly good, but some data of the new NodeBB seems not purged - some user logged in as another one, and posts content merged or replaced.

However if the NodeBB is a new installation these problems should be gone.

**Comment by bdharrington7** [comment]
@phoenixlzx so.. are you saying it worked after setting up a clean NodeBB?

**Comment by akhoury** [comment]
yea, this is not really designed to merge data. In fact, the importer will FLUSH or __wipe out__ your existing nodebb DB - if the import process was interrupted, in most case it can resume (it some it cannot)

**Comment by phoenixlzx** [comment]
@bdharrington7 @akhoury Yeah, my vanillaforums converted to NodeBB successfully with a new installation. Only one problem found - the topic ID changed.

Maybe you need to add a instruction of these.

**Comment by akhoury** [comment]
@phoenixlzx - ALL ids will change, Topics, Users, Posts, Categories, Messages  etc.. 
but that totally expected and should NOT be problem, as the Importer will handle all of these changes.
https://github.com/akhoury/nodebb-plugin-import/blob/master/write-my-own-exporter.md#terminology

However, 1 issue might come up if you care about redirecting URLs, you can download a redirect.map.json file and use it to redirect your URLs, read this section
https://github.com/akhoury/nodebb-plugin-import#imported-now-what

**Comment by bdharrington7** [comment]
@phoenixlzx @fr3em1nd Please note that I had to back out some works in progress from the master branch (which shouldn't affect you if you pulled the version I linked to), but just to be safe, please delete and re-clone the master branch if you're going to be using the importer for vanilla any more

**Comment by akhoury** [comment]
closing.. 
all new vanilla issues should be filed under @bdharrington7 's repo
https://github.com/bdharrington7/nodebb-plugin-import-vanilla
which im watching as well
